--- @module "krsnvim.krsnvimtranspiler"
--- Comprehensive Transpiler suite for `krsnvimscript` (*.krsnvim).
--- Programmatically converts `.krsnvim` scripts into 100% equivalent `.sh` (Bash) and `.ps1` (PowerShell) scripts
--- using native OS CLI tools (`curl`, `mkdir`, `jq`, `Invoke-RestMethod`, `New-Item`, `Get-Content`, etc.).
--- Supports functions, parameters, advanced loops, CLI arguments/menus, YAML/TOML, and error assertions.
---
--- @example
--- local transpiler = import("krsnvimtranspiler")
--- transpiler.export_both("test.krsnvim") -- generates test.sh and test.ps1
local M = {}

local fs = require("krsnvim.fs")

--- Splits a comma-separated argument list on top-level commas only, ignoring
--- commas nested inside `{}` or `()` (e.g. a table-literal or call argument).
--- @param args string
--- @return string[]
local function split_args(args)
	local parts, depth, current = {}, 0, ""
	for i = 1, #args do
		local c = args:sub(i, i)
		if c == "{" or c == "(" then depth = depth + 1
		elseif c == "}" or c == ")" then depth = depth - 1 end
		if c == "," and depth == 0 then
			table.insert(parts, current)
			current = ""
		else
			current = current .. c
		end
	end
	if current:match("%S") then table.insert(parts, current) end
	return parts
end

--- Joins source lines whose parens haven't balanced yet (e.g. a function call
--- whose table-literal argument spans multiple lines) into one logical line,
--- so the per-line transpilers below can pattern-match the whole call at once.
--- @param code string
--- @return string
local function join_multiline_calls(code)
	local out_lines = {}
	local pending, depth = nil, 0
	for line in code:gmatch("[^\r\n]+") do
		local _, opens = line:gsub("%(", "")
		local _, closes = line:gsub("%)", "")
		if pending then
			pending = pending .. " " .. line:match("^%s*(.-)%s*$")
		else
			pending = line
		end
		depth = depth + opens - closes
		if depth <= 0 then
			table.insert(out_lines, pending)
			pending, depth = nil, 0
		end
	end
	if pending then
		table.insert(out_lines, pending)
	end
	return table.concat(out_lines, "\n")
end

--- Converts a Lua expression fragment into PowerShell: `obj:method(` -> `obj.method(`,
--- and bare `word.word`/`word` identifiers -> `$word.word`/`$word` (skips string literals,
--- numbers, already-`$`-prefixed vars, and `true`/`false`/`nil`).
--- @param expr string
--- @return string
local function ps1_expr(expr)
	if not expr then return expr end
	expr = expr:gsub("([%w_]+):([%w_]+)%(", "%1.%2(")
	expr = expr:gsub("[%w_]+%.?[%w_]*", function(word)
		if word:match("^%d") or word == "true" or word == "false" or word == "nil" then
			return word
		end
		return "$" .. word
	end)
	expr = expr:gsub('"[^"]*"', function(s) return s end)
	return expr
end

--- Helper to convert Lua table literal to PowerShell Hashtable syntax (@{...}).
--- @param lua_tbl_str string
--- @return string
local function lua_tbl_to_ps1(lua_tbl_str)
	if not lua_tbl_str then return "" end
	local s = lua_tbl_str:match("^%s*{?(.-)}?%s*$")
	if not s or s == "" then return "@{}" end
	local items = {}
	for kv in s:gmatch("[^,]+") do
		local k, v = kv:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
		if k and v then
			if v == "true" then v = "$true"
			elseif v == "false" then v = "$false"
			elseif v == "nil" then v = "$null"
			end
			table.insert(items, '"' .. k .. '"=' .. v)
		else
			table.insert(items, kv)
		end
	end
	return "@{" .. table.concat(items, "; ") .. "}"
end

--- Helper to convert Lua table literal to JSON string literal for Bash.
--- @param lua_tbl_str string
--- @return string
local function lua_tbl_to_json(lua_tbl_str)
	if not lua_tbl_str then return '""' end
	local s = lua_tbl_str:match("^%s*{?(.-)}?%s*$")
	if not s or s == "" then return '"{}"' end
	local items = {}
	for kv in s:gmatch("[^,]+") do
		local k, v = kv:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
		if k and v then
			table.insert(items, '"' .. k .. '": ' .. v)
		else
			table.insert(items, kv)
		end
	end
	return '\'{' .. table.concat(items, ", ") .. '}\''
end

--- Transpiles `.krsnvim` Lua code string into Bash script (`.sh`).
--- @param code string Full Lua code string of a .krsnvim script.
--- @return string bash_script Equivalent Bash script.
function M.to_sh(code)
	local lines = {}
	table.insert(lines, "#!/usr/bin/env bash")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "# Transpiled from krsnvimscript (.krsnvim) -> Bash (.sh)")
	table.insert(lines, "# Automatically generated by krsnvimtranspiler")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "set -e")
	table.insert(lines, "")

	local block_stack = {}

	for line in join_multiline_calls(code):gmatch("[^\r\n]+") do
		local trimmed = line:match("^%s*(.-)%s*$")
		local indent = line:match("^(%s*)") or ""

		-- Skip or comment out require/import lines
		if trimmed:match("^local%s+[%w_]+%s*=%s*require%(") or trimmed:match("^local%s+[%w_]+%s*=%s*import%(") or trimmed:match("^require%(") or trimmed:match("^import%(") then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed .. " (mapped to native CLI tools)")
		
		-- Comments: -- comment -> # comment
		elseif trimmed:sub(1, 2) == "--" then
			local comment_text = trimmed:sub(3):match("^%s*(.-)%s*$")
			table.insert(lines, indent .. "# " .. comment_text)

		-- Empty lines
		elseif trimmed == "" then
			table.insert(lines, "")

		-- Function definitions: function fn_name(arg1, arg2)
		elseif trimmed:match("^function%s+([%w_]+)%s*%((.*)%)") then
			local fn_name, params_str = trimmed:match("^function%s+([%w_]+)%s*%((.*)%)")
			table.insert(block_stack, "function")
			table.insert(lines, indent .. fn_name .. "() {")
			local idx = 1
			for param in params_str:gmatch("[^,]+") do
				param = param:match("^%s*(.-)%s*$")
				if param ~= "" then
					table.insert(lines, indent .. "  local " .. param .. '="$' .. idx .. '"')
					idx = idx + 1
				end
			end

		-- Local function definitions: local function fn_name(arg1, arg2)
		elseif trimmed:match("^local%s+function%s+([%w_]+)%s*%((.*)%)") then
			local fn_name, params_str = trimmed:match("^local%s+function%s+([%w_]+)%s*%((.*)%)")
			table.insert(block_stack, "function")
			table.insert(lines, indent .. fn_name .. "() {")
			local idx = 1
			for param in params_str:gmatch("[^,]+") do
				param = param:match("^%s*(.-)%s*$")
				if param ~= "" then
					table.insert(lines, indent .. "  local " .. param .. '="$' .. idx .. '"')
					idx = idx + 1
				end
			end

		-- print(...) -> echo ...
		elseif trimmed:match("^print%((.*)%)") then
			local args = trimmed:match("^print%((.*)%)")
			local echoed = {}
			for arg in args:gmatch("[^,]+") do
				arg = arg:match("^%s*(.-)%s*$")
				if arg:sub(1, 1) == '"' and arg:sub(-1) == '"' then
					table.insert(echoed, arg:sub(2, -2))
				elseif arg:sub(1, 1) == "'" and arg:sub(-1) == "'" then
					table.insert(echoed, arg:sub(2, -2))
				else
					table.insert(echoed, "${" .. arg .. "}")
				end
			end
			table.insert(lines, indent .. 'echo "' .. table.concat(echoed, " ") .. '"')

		-- console.log(...) / console.info(...) -> echo ...
		elseif trimmed:match("^console%.[%w_]+%((.*)%)%s*$") then
			local args = trimmed:match("^console%.[%w_]+%((.*)%)%s*$")
			local echoed = {}
			for _, raw in ipairs(split_args(args)) do
				local arg = raw:match("^%s*(.-)%s*$")
				if arg:sub(1, 1) == '"' and arg:sub(-1) == '"' then
					table.insert(echoed, arg:sub(2, -2))
				elseif arg:sub(1, 1) == "'" and arg:sub(-1) == "'" then
					table.insert(echoed, arg:sub(2, -2))
				elseif arg:sub(1, 1) == "{" then
					table.insert(echoed, lua_tbl_to_json(arg))
				else
					table.insert(echoed, "${" .. arg .. "}")
				end
			end
			table.insert(lines, indent .. 'echo "' .. table.concat(echoed, " ") .. '"')

		-- error(msg) -> echo "msg" >&2; exit 1
		elseif trimmed:match("^error%((.*)%)") then
			local err_msg = trimmed:match("^error%((.*)%)")
			table.insert(lines, indent .. 'echo ' .. err_msg .. ' >&2')
			table.insert(lines, indent .. 'exit 1')

		-- assert(cond, msg) -> [ cond ] || { echo "msg" >&2; exit 1; }
		elseif trimmed:match("^assert%((.*)%)") then
			local args = trimmed:match("^assert%((.*)%)")
			local cond, msg = args:match("^(.-),%s*(.*)$")
			cond = cond or args
			msg = msg or '"Assertion failed"'
			table.insert(lines, indent .. '[ ' .. cond .. ' ] || { echo ' .. msg .. ' >&2; exit 1; }')

		-- fs.mkdir(path) -> mkdir -p path
		elseif trimmed:match("fs%.mkdir%((.*)%)") then
			local path_arg = trimmed:match("fs%.mkdir%((.*)%)")
			table.insert(lines, indent .. "mkdir -p " .. path_arg)

		-- fs.write(path, content) -> echo content > path
		elseif trimmed:match("fs%.write%((.*),%s*(.*)%)") then
			local path_arg, content_arg = trimmed:match("fs%.write%((.*),%s*(.*)%)")
			if content_arg:sub(1, 1) == '"' or content_arg:sub(1, 1) == "'" then
				table.insert(lines, indent .. 'echo ' .. content_arg .. ' > ' .. path_arg)
			else
				table.insert(lines, indent .. 'echo "${' .. content_arg .. '}" > ' .. path_arg)
			end

		-- fs.read(path) -> cat path
		elseif trimmed:match("fs%.read%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*fs%.read%((.*)%)")
			if var then
				table.insert(lines, indent .. var .. '=$(cat ' .. path_arg .. ')')
			else
				local path = trimmed:match("fs%.read%((.*)%)")
				table.insert(lines, indent .. 'cat ' .. path)
			end

		-- json.encode(obj) -> echo obj | jq -c .
		elseif trimmed:match("json%.encode%((.*)%)") then
			local var, obj = trimmed:match("^local%s+([%w_]+)%s*=%s*json%.encode%((.*)%)")
			if var then
				local json_payload = obj:sub(1, 1) == "{" and lua_tbl_to_json(obj) or obj
				table.insert(lines, indent .. var .. '=$(echo ' .. json_payload .. ' | jq -c .)')
			else
				local obj_arg = trimmed:match("json%.encode%((.*)%)")
				local json_payload = obj_arg:sub(1, 1) == "{" and lua_tbl_to_json(obj_arg) or obj_arg
				table.insert(lines, indent .. 'echo ' .. json_payload .. ' | jq -c .')
			end

		-- json.load(path) -> cat path | jq .
		elseif trimmed:match("json%.load%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*json%.load%((.*)%)")
			if var then
				table.insert(lines, indent .. var .. '=$(cat ' .. path_arg .. ')')
			else
				local path = trimmed:match("json%.load%((.*)%)")
				table.insert(lines, indent .. 'cat ' .. path .. ' | jq .')
			end

		-- yaml.load(path) -> python3 -c "import yaml..." path
		elseif trimmed:match("yaml%.load%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*yaml%.load%((.*)%)")
			local py_cmd = 'python3 -c "import yaml, json, sys; print(json.dumps(yaml.safe_load(open(sys.argv[1]))))" ' .. path_arg
			if var then
				table.insert(lines, indent .. var .. '=$(' .. py_cmd .. ')')
			else
				table.insert(lines, indent .. py_cmd)
			end

		-- toml.load(path) -> python3 -c "import tomllib..." path
		elseif trimmed:match("toml%.load%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*toml%.load%((.*)%)")
			local py_cmd = 'python3 -c "import tomllib, json, sys; print(json.dumps(tomllib.load(open(sys.argv[1], \'rb\'))))" ' .. path_arg
			if var then
				table.insert(lines, indent .. var .. '=$(' .. py_cmd .. ')')
			else
				table.insert(lines, indent .. py_cmd)
			end

		-- fetch.get(url) / fetch.json(url) -> curl -sSL url
		elseif trimmed:match("fetch%.get%((.*)%)") or trimmed:match("fetch%.json%((.*)%)") then
			local var, url_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*fetch%..-%((.*)%)")
			if var then
				table.insert(lines, indent .. var .. '=$(curl -sSL ' .. url_arg .. ')')
			else
				local url = trimmed:match("fetch%..-%((.*)%)")
				table.insert(lines, indent .. 'curl -sSL ' .. url)
			end

		-- $ "cmd" or terminal.exec("cmd") -> cmd
		elseif trimmed:match("^%s*%$%s*%((.*)%)") or trimmed:match("^%s*terminal%.exec%((.*)%)") or trimmed:match("^%s*terminal%.run%((.*)%)") then
			local cmd_arg = trimmed:match("%((.*)%)")
			cmd_arg = cmd_arg:gsub('^"', ''):gsub('"$', ''):gsub("^'", ''):gsub("'$", '')
			table.insert(lines, indent .. cmd_arg)

		-- local var = val
		elseif trimmed:match("^local%s+([%w_]+)%s*=%s*(.*)$") then
			local var, val = trimmed:match("^local%s+([%w_]+)%s*=%s*(.*)$")
			if val:sub(1, 1) == '"' and val:sub(-1) == '"' then
				table.insert(lines, indent .. var .. "=" .. val)
			elseif val == "true" or val == "false" then
				table.insert(lines, indent .. var .. '="' .. val .. '"')
			else
				table.insert(lines, indent .. var .. "=" .. val)
			end

		-- Loops: for i = start, stop do
		elseif trimmed:match("^for%s+([%w_]+)%s*=%s*(%d+)%s*,%s*(%d+)%s+do$") then
			local var, start_val, stop_val = trimmed:match("^for%s+([%w_]+)%s*=%s*(%d+)%s*,%s*(%d+)%s+do$")
			table.insert(block_stack, "loop")
			table.insert(lines, indent .. "for ((" .. var .. "=" .. start_val .. "; " .. var .. "<=" .. stop_val .. "; " .. var .. "++)); do")

		-- Loops: for _, item in ipairs(list) do
		elseif trimmed:match("^for%s+[%w_]+%s*,%s*([%w_]+)%s+in%s+ipairs%(([%w_]+)%)%s+do$") then
			local item_var, list_var = trimmed:match("^for%s+[%w_]+%s*,%s*([%w_]+)%s+in%s+ipairs%(([%w_]+)%)%s+do$")
			table.insert(block_stack, "loop")
			table.insert(lines, indent .. 'for ' .. item_var .. ' in "${' .. list_var .. '[@]}"; do')

		-- Loops: while cond do
		elseif trimmed:match("^while%s+(.-)%s+do$") then
			local cond = trimmed:match("^while%s+(.-)%s+do$")
			table.insert(block_stack, "loop")
			table.insert(lines, indent .. "while [ " .. cond .. " ]; do")

		-- Control Flow: if ... then
		elseif trimmed:match("^if%s+(.-)%s+then$") then
			local cond = trimmed:match("^if%s+(.-)%s+then$")
			table.insert(block_stack, "if")
			if cond:match("fs%.exists%((.*)%)") then
				local p = cond:match("fs%.exists%((.*)%)")
				table.insert(lines, indent .. "if [ -e " .. p .. " ]; then")
			else
				table.insert(lines, indent .. "if [ " .. cond .. " ]; then")
			end

		-- Control Flow: elseif ... then
		elseif trimmed:match("^elseif%s+(.-)%s+then$") then
			local cond = trimmed:match("^elseif%s+(.-)%s+then$")
			if cond:match("fs%.exists%((.*)%)") then
				local p = cond:match("fs%.exists%((.*)%)")
				table.insert(lines, indent .. "elif [ -e " .. p .. " ]; then")
			else
				table.insert(lines, indent .. "elif [ " .. cond .. " ]; then")
			end

		-- Control Flow: else
		elseif trimmed == "else" then
			table.insert(lines, indent .. "else")

		-- Block End: end
		elseif trimmed == "end" or trimmed == "}" then
			local last_block = table.remove(block_stack) or "if"
			if last_block == "if" then
				table.insert(lines, indent .. "fi")
			elseif last_block == "function" or last_block == "fn" then
				table.insert(lines, indent .. "}")
			else
				table.insert(lines, indent .. "done")
			end

		else
			-- Fallback: pass line as is with -- turned to #
			table.insert(lines, (line:gsub("^%s*%-%-", indent .. "#")))
		end
	end

	return table.concat(lines, "\n")
end

--- Transpiles `.krsnvim` Lua code string into PowerShell script (`.ps1`).
--- @param code string Full Lua code string of a .krsnvim script.
--- @return string ps1_script Equivalent PowerShell script.
function M.to_ps1(code)
	local lines = {}
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "# Transpiled from krsnvimscript (.krsnvim) -> PowerShell (.ps1)")
	table.insert(lines, "# Automatically generated by krsnvimtranspiler")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "$ErrorActionPreference = 'Stop'")
	table.insert(lines, "")

	for line in join_multiline_calls(code):gmatch("[^\r\n]+") do
		local trimmed = line:match("^%s*(.-)%s*$")
		local indent = line:match("^(%s*)") or ""

		-- Skip or comment out require/import lines
		if trimmed:match("^local%s+[%w_]+%s*=%s*require%(") or trimmed:match("^local%s+[%w_]+%s*=%s*import%(") or trimmed:match("^require%(") or trimmed:match("^import%(") then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed .. " (mapped to native PowerShell cmdlets)")

		-- Comments: -- comment -> # comment
		elseif trimmed:sub(1, 2) == "--" then
			local comment_text = trimmed:sub(3):match("^%s*(.-)%s*$")
			table.insert(lines, indent .. "# " .. comment_text)

		-- Empty lines
		elseif trimmed == "" then
			table.insert(lines, "")

		-- Function definitions: function fn_name(arg1, arg2)
		elseif trimmed:match("^function%s+([%w_]+)%s*%((.*)%)") or trimmed:match("^local%s+function%s+([%w_]+)%s*%((.*)%)") then
			local fn_name, params_str = trimmed:match("function%s+([%w_]+)%s*%((.*)%)")
			local ps_params = {}
			for param in params_str:gmatch("[^,]+") do
				param = param:match("^%s*(.-)%s*$")
				if param ~= "" then
					table.insert(ps_params, "$" .. param)
				end
			end
			table.insert(lines, indent .. "function " .. fn_name .. "(" .. table.concat(ps_params, ", ") .. ") {")

		-- print(...) -> Write-Host ...
		elseif trimmed:match("^print%((.*)%)") then
			local args = trimmed:match("^print%((.*)%)")
			local parts = {}
			for part in args:gmatch("[^,]+") do
				part = part:match("^%s*(.-)%s*$")
				if part:sub(1, 1) == '"' and part:sub(-1) == '"' then
					table.insert(parts, part)
				elseif part:sub(1, 1) == "'" and part:sub(-1) == "'" then
					table.insert(parts, part)
				else
					if part:sub(1, 1) ~= "$" then
						table.insert(parts, "$" .. part)
					else
						table.insert(parts, part)
					end
				end
			end
			table.insert(lines, indent .. "Write-Host " .. table.concat(parts, " "))

		-- console.log(...) / console.info(...) -> Write-Host ...
		elseif trimmed:match("^console%.[%w_]+%((.*)%)%s*$") then
			local args = trimmed:match("^console%.[%w_]+%((.*)%)%s*$")
			local parts = {}
			for _, raw in ipairs(split_args(args)) do
				local part = raw:match("^%s*(.-)%s*$")
				if part:sub(1, 1) == '"' or part:sub(1, 1) == "'" then
					table.insert(parts, part)
				elseif part:sub(1, 1) == "{" then
					table.insert(parts, lua_tbl_to_ps1(part))
				else
					table.insert(parts, ps1_expr(part))
				end
			end
			table.insert(lines, indent .. "Write-Host " .. table.concat(parts, " "))

		-- error(msg) -> throw msg
		elseif trimmed:match("^error%((.*)%)") then
			local err_msg = trimmed:match("^error%((.*)%)")
			table.insert(lines, indent .. "throw " .. err_msg)

		-- assert(cond, msg) -> if (-not (cond)) { throw msg }
		elseif trimmed:match("^assert%((.*)%)") then
			local args = trimmed:match("^assert%((.*)%)")
			local cond, msg = args:match("^(.-),%s*(.*)$")
			cond = cond or args
			msg = msg or '"Assertion failed"'
			table.insert(lines, indent .. "if (-not (" .. cond .. ")) { throw " .. msg .. " }")

		-- fs.mkdir(path) -> New-Item -ItemType Directory -Force -Path path | Out-Null
		elseif trimmed:match("fs%.mkdir%((.*)%)") then
			local path_arg = trimmed:match("fs%.mkdir%((.*)%)")
			table.insert(lines, indent .. "New-Item -ItemType Directory -Force -Path " .. path_arg .. " | Out-Null")

		-- fs.write(path, content) -> Set-Content -Path path -Value content
		elseif trimmed:match("fs%.write%((.*),%s*(.*)%)") then
			local path_arg, content_arg = trimmed:match("fs%.write%((.*),%s*(.*)%)")
			table.insert(lines, indent .. "Set-Content -Path " .. path_arg .. " -Value " .. content_arg)

		-- fs.read(path) -> Get-Content -Raw path
		elseif trimmed:match("fs%.read%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*fs%.read%((.*)%)")
			if var then
				table.insert(lines, indent .. "$" .. var .. " = Get-Content -Raw " .. path_arg)
			else
				local path = trimmed:match("fs%.read%((.*)%)")
				table.insert(lines, indent .. "Get-Content -Raw " .. path)
			end

		-- json.encode(obj) -> obj | ConvertTo-Json -Compress
		elseif trimmed:match("json%.encode%((.*)%)") then
			local var, obj = trimmed:match("^local%s+([%w_]+)%s*=%s*json%.encode%((.*)%)")
			local ps1_obj = obj:sub(1, 1) == "{" and lua_tbl_to_ps1(obj) or (obj:sub(1,1) == "$" and obj or "$" .. obj)
			if var then
				table.insert(lines, indent .. "$" .. var .. " = (" .. ps1_obj .. " | ConvertTo-Json -Compress)")
			else
				local obj_arg = trimmed:match("json%.encode%((.*)%)")
				local ps1_arg = obj_arg:sub(1, 1) == "{" and lua_tbl_to_ps1(obj_arg) or (obj_arg:sub(1,1) == "$" and obj_arg or "$" .. obj_arg)
				table.insert(lines, indent .. ps1_arg .. " | ConvertTo-Json -Compress")
			end

		-- json.load(path) -> Get-Content -Raw path | ConvertFrom-Json
		elseif trimmed:match("json%.load%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*json%.load%((.*)%)")
			if var then
				table.insert(lines, indent .. "$" .. var .. " = (Get-Content -Raw " .. path_arg .. " | ConvertFrom-Json)")
			else
				local path = trimmed:match("json%.load%((.*)%)")
				table.insert(lines, indent .. "Get-Content -Raw " .. path .. " | ConvertFrom-Json")
			end

		-- yaml.load(path) -> Get-Content -Raw path | ConvertFrom-Json
		elseif trimmed:match("yaml%.load%((.*)%)") then
			local var, path_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*yaml%.load%((.*)%)")
			if var then
				table.insert(lines, indent .. "$" .. var .. " = (Get-Content -Raw " .. path_arg .. " | ConvertFrom-Json)")
			else
				local path = trimmed:match("yaml%.load%((.*)%)")
				table.insert(lines, indent .. "Get-Content -Raw " .. path .. " | ConvertFrom-Json")
			end

		-- fetch.get(url) -> (Invoke-WebRequest -Uri url -UseBasicParsing).Content
		-- fetch.json(url) -> Invoke-RestMethod -Uri url
		elseif trimmed:match("fetch%.get%((.*)%)") then
			local var, url_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*fetch%.get%((.*)%)")
			if var then
				table.insert(lines, indent .. "$" .. var .. " = (Invoke-WebRequest -Uri " .. url_arg .. " -UseBasicParsing).Content")
			else
				local url = trimmed:match("fetch%.get%((.*)%)")
				table.insert(lines, indent .. "(Invoke-WebRequest -Uri " .. url .. " -UseBasicParsing).Content")
			end
		elseif trimmed:match("fetch%.json%((.*)%)") then
			local var, url_arg = trimmed:match("^local%s+([%w_]+)%s*=%s*fetch%.json%((.*)%)")
			if var then
				table.insert(lines, indent .. "$" .. var .. " = Invoke-RestMethod -Uri " .. url_arg)
			else
				local url = trimmed:match("fetch%.json%((.*)%)")
				table.insert(lines, indent .. "Invoke-RestMethod -Uri " .. url)
			end

		-- $ "cmd" or terminal.exec("cmd") -> cmd
		elseif trimmed:match("^%s*%$%s*%((.*)%)") or trimmed:match("^%s*terminal%.exec%((.*)%)") or trimmed:match("^%s*terminal%.run%((.*)%)") then
			local cmd_arg = trimmed:match("%((.*)%)")
			cmd_arg = cmd_arg:gsub('^"', ''):gsub('"$', ''):gsub("^'", ''):gsub("'$", '')
			table.insert(lines, indent .. cmd_arg)

		-- local var = val -> $var = val
		elseif trimmed:match("^local%s+([%w_]+)%s*=%s*(.*)$") then
			local var, val = trimmed:match("^local%s+([%w_]+)%s*=%s*(.*)$")
			val = val:gsub("true", "$true"):gsub("false", "$false"):gsub("nil", "$null")
			table.insert(lines, indent .. "$" .. var .. " = " .. val)

		-- Loops: for i = start, stop do
		elseif trimmed:match("^for%s+([%w_]+)%s*=%s*(%d+)%s*,%s*(%d+)%s+do$") then
			local var, start_val, stop_val = trimmed:match("^for%s+([%w_]+)%s*=%s*(%d+)%s*,%s*(%d+)%s+do$")
			table.insert(lines, indent .. "for ($" .. var .. " = " .. start_val .. "; $" .. var .. " -le " .. stop_val .. "; $" .. var .. "++) {")

		-- Loops: for _, item in ipairs(list) do
		elseif trimmed:match("^for%s+[%w_]+%s*,%s*([%w_]+)%s+in%s+ipairs%(([%w_]+)%)%s+do$") then
			local item_var, list_var = trimmed:match("^for%s+[%w_]+%s*,%s*([%w_]+)%s+in%s+ipairs%(([%w_]+)%)%s+do$")
			table.insert(lines, indent .. "foreach ($" .. item_var .. " in $" .. list_var .. ") {")

		-- Loops: while cond do
		elseif trimmed:match("^while%s+(.-)%s+do$") then
			local cond = trimmed:match("^while%s+(.-)%s+do$")
			table.insert(lines, indent .. "while (" .. cond .. ") {")

		-- Control Flow: if ... then
		elseif trimmed:match("^if%s+(.-)%s+then$") then
			local cond = trimmed:match("^if%s+(.-)%s+then$")
			if cond:match("fs%.exists%((.*)%)") then
				local p = cond:match("fs%.exists%((.*)%)")
				table.insert(lines, indent .. "if (Test-Path " .. p .. ") {")
			else
				table.insert(lines, indent .. "if (" .. ps1_expr(cond) .. ") {")
			end

		-- Control Flow: elseif ... then
		elseif trimmed:match("^elseif%s+(.-)%s+then$") then
			local cond = trimmed:match("^elseif%s+(.-)%s+then$")
			if cond:match("fs%.exists%((.*)%)") then
				local p = cond:match("fs%.exists%((.*)%)")
				table.insert(lines, indent .. "} elseif (Test-Path " .. p .. ") {")
			else
				table.insert(lines, indent .. "} elseif (" .. ps1_expr(cond) .. ") {")
			end

		-- Control Flow: else
		elseif trimmed == "else" then
			table.insert(lines, indent .. "} else {")

		-- Block End: end
		elseif trimmed == "end" or trimmed == "}" then
			table.insert(lines, indent .. "}")

		else
			-- Fallback: convert local variable names to $var and comments to #
			local l = line:gsub("^%s*%-%-", indent .. "#")
			table.insert(lines, l)
		end
	end

	return table.concat(lines, "\n")
end

--- Exports a given .krsnvim script file to .sh (Bash) script.
--- @param filepath string Path to source .krsnvim script file.
--- @param outpath string|nil Target .sh file path. Defaults to replacing .krsnvim with .sh.
--- @return string generated_path Path of generated .sh file.
function M.export_sh(filepath, outpath)
	if not filepath or filepath == "" then
		if vim and vim.api then
			filepath = vim.api.nvim_buf_get_name(0)
		end
	end
	if not filepath or filepath == "" then
		error("krsnvimtranspiler: No source file provided for export")
	end

	local content = fs.read(filepath)
	local sh_code = M.to_sh(content)

	if not outpath or outpath == "" then
		outpath = filepath:gsub("%.krsnvim$", "") .. ".sh"
		if outpath == filepath then
			outpath = filepath .. ".sh"
		end
	end

	fs.write(outpath, sh_code)
	if vim and vim.notify then
		vim.notify("🦊 Exported " .. vim.fn.fnamemodify(filepath, ":t") .. " -> " .. vim.fn.fnamemodify(outpath, ":t"), vim.log.levels.INFO)
	end
	return outpath
end

--- Exports a given .krsnvim script file to .ps1 (PowerShell) script.
--- @param filepath string Path to source .krsnvim script file.
--- @param outpath string|nil Target .ps1 file path. Defaults to replacing .krsnvim with .ps1.
--- @return string generated_path Path of generated .ps1 file.
function M.export_ps1(filepath, outpath)
	if not filepath or filepath == "" then
		if vim and vim.api then
			filepath = vim.api.nvim_buf_get_name(0)
		end
	end
	if not filepath or filepath == "" then
		error("krsnvimtranspiler: No source file provided for export")
	end

	local content = fs.read(filepath)
	local ps1_code = M.to_ps1(content)

	if not outpath or outpath == "" then
		outpath = filepath:gsub("%.krsnvim$", "") .. ".ps1"
		if outpath == filepath then
			outpath = filepath .. ".ps1"
		end
	end

	fs.write(outpath, ps1_code)
	if vim and vim.notify then
		vim.notify("🦊 Exported " .. vim.fn.fnamemodify(filepath, ":t") .. " -> " .. vim.fn.fnamemodify(outpath, ":t"), vim.log.levels.INFO)
	end
	return outpath
end

--- Exports a given .krsnvim script file to BOTH .sh and .ps1 scripts simultaneously.
--- @param filepath string|nil Path to source .krsnvim script file. Defaults to current active buffer.
--- @return table paths { sh = string, ps1 = string }
function M.export_both(filepath)
	if not filepath or filepath == "" then
		if vim and vim.api then
			filepath = vim.api.nvim_buf_get_name(0)
		end
	end
	local sh_path = M.export_sh(filepath)
	local ps1_path = M.export_ps1(filepath)
	return { sh = sh_path, ps1 = ps1_path }
end

return M
