-- ============================================================================
-- KRSNVIMSCRIPT TRANSPILER -- PowerShell (.ps1) Generator
-- ============================================================================

local common = require("krs.lib.krsnvim.krsnvimtranspiler.common")

local M = {}

local LUA_KEYWORDS = common.LUA_KEYWORDS
local join_multiline_calls = common.join_multiline_calls
local format_ps1_val = common.format_ps1_val
local lua_tbl_to_ps1 = common.lua_tbl_to_ps1
local to_ps1_expr = common.to_ps1_expr
local split_args = common.split_args

--- Transpiles `.krsnvim` Lua code string into PowerShell script (`.ps1`).
--- @param code string Full Lua code string of a .krsnvim script.
--- @return string ps1_script Equivalent PowerShell script.
function M.to_ps1(code)
	local lines = {}
	local block_stack = {}
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "# Transpiled from krsnvimscript (.krsnvim) -> PowerShell (.ps1)")
	table.insert(lines, "# Automatically generated by krsnvimtranspiler")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "$ErrorActionPreference = 'Stop'")
	table.insert(lines, "")

	for line in join_multiline_calls(code):gmatch("[^\r\n]+") do
		local trimmed = line:match("^%s*(.-)%s*$")
		local indent = line:match("^(%s*)") or ""

		if
			trimmed:match("^local%s+[%w_]+%s*=%s*require%(")
			or trimmed:match("^local%s+[%w_]+%s*=%s*import%(")
			or trimmed:match("^require%(")
			or trimmed:match("^import%(")
		then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed .. " (mapped to native PowerShell cmdlets)")

		elseif trimmed:sub(1, 2) == "--" then
			local comment_text = trimmed:sub(3):match("^%s*(.-)%s*$")
			table.insert(lines, indent .. "# " .. comment_text)

		elseif trimmed == "" then
			table.insert(lines, "")

		elseif
			trimmed:match("^[%w_]*%.?beforeAll%s*%(")
			or trimmed:match("^[%w_]*%.?afterAll%s*%(")
			or trimmed:match("^[%w_]*%.?beforeEach%s*%(")
			or trimmed:match("^[%w_]*%.?afterEach%s*%(")
		then
			table.insert(block_stack, "noop")

		elseif trimmed:match("^describe%s*%(") or trimmed:match("^[%w_]+%.describe%s*%(") then
			local suite_name = trimmed:match('describe%s*%("%s*(.-)%s*"')
				or trimmed:match("describe%s*%('%s*(.-)%s*'")
				or "Test Suite"
			table.insert(block_stack, "noop")
			table.insert(lines, indent .. 'Write-Host "📦 Suite: ' .. suite_name .. '"')

		elseif trimmed:match("^[%w_]+%.run%s*%(") or trimmed:match("^run%s*%(") then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed)

		elseif
			trimmed:match("^it%s*%(")
			or trimmed:match("^test%s*%(")
			or trimmed:match("^[%w_]+%.it%s*%(")
			or trimmed:match("^[%w_]+%.test%s*%(")
		then
			local test_name = trimmed:match('it%s*%("%s*(.-)%s*"')
				or trimmed:match('test%s*%("%s*(.-)%s*"')
				or trimmed:match("it%s*%('%s*(.-)%s*'")
				or trimmed:match("test%s*%('%s*(.-)%s*'")
				or "Test"
			table.insert(block_stack, "noop")
			table.insert(lines, indent .. 'Write-Host "  ✓ ' .. test_name .. '"')

		elseif trimmed:match("^expect%s*%(") then
			local is_inv = trimmed:find("%.isNot%.")
				or trimmed:find('%["not"%]')
				or trimmed:find("%.not%.")
				or trimmed:find("%.not_%.")

			if trimmed:find("%.toBe%s*%(") or trimmed:find("%.toEqual%s*%(") then
				local act, exp = trimmed:match("expect%s*%((.-)%)%..-toBe%s*%((.-)%)")
				if not act then
					act, exp = trimmed:match("expect%s*%((.-)%)%..-toEqual%s*%((.-)%)")
				end
				if act and exp then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if ("
								.. format_ps1_val(act)
								.. " -eq "
								.. format_ps1_val(exp)
								.. ') { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(
							lines,
							indent
								.. "if ("
								.. format_ps1_val(act)
								.. " -ne "
								.. format_ps1_val(exp)
								.. ') { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toBeTruthy%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(lines, indent .. "if (" .. format_ps1_val(act) .. ') { Write-Error "Expect failed"; exit 1 }')
					else
						table.insert(
							lines,
							indent .. "if (-not (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toBeFalsy%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent .. "if (-not (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(lines, indent .. "if (" .. format_ps1_val(act) .. ') { Write-Error "Expect failed"; exit 1 }')
					end
				end
			elseif
				trimmed:find("%.toBeNil%s*%(")
				or trimmed:find("%.toBeNull%s*%(")
				or trimmed:find("%.toBeUndefined%s*%(")
			then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent .. "if ($null -eq (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(
							lines,
							indent .. "if ($null -ne (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toBeDefined%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent .. "if ($null -ne (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(
							lines,
							indent .. "if ($null -eq (" .. format_ps1_val(act) .. ')) { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toContain%s*%(") then
				local act, item = trimmed:match("expect%s*%((.-)%)%..-toContain%s*%((.-)%)")
				if act and item then
					local clean_item = item:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if ("
								.. format_ps1_val(act)
								.. ' -like "*'
								.. clean_item
								.. '*") { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(
							lines,
							indent
								.. "if ("
								.. format_ps1_val(act)
								.. ' -notlike "*'
								.. clean_item
								.. '*") { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toHaveLength%s*%(") then
				local act, len = trimmed:match("expect%s*%((.-)%)%..-toHaveLength%s*%((.-)%)")
				if act and len then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if (("
								.. format_ps1_val(act)
								.. ").Count -eq "
								.. format_ps1_val(len)
								.. ') { Write-Error "Expect failed"; exit 1 }'
						)
					else
						table.insert(
							lines,
							indent
								.. "if (("
								.. format_ps1_val(act)
								.. ").Count -ne "
								.. format_ps1_val(len)
								.. ') { Write-Error "Expect failed"; exit 1 }'
						)
					end
				end
			elseif trimmed:find("%.toBeGreaterThan%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeGreaterThan%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if ("
							.. format_ps1_val(act)
							.. " -le "
							.. format_ps1_val(num)
							.. ') { Write-Error "Expect failed"; exit 1 }'
					)
				end
			elseif trimmed:find("%.toBeGreaterThanOrEqual%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeGreaterThanOrEqual%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if ("
							.. format_ps1_val(act)
							.. " -lt "
							.. format_ps1_val(num)
							.. ') { Write-Error "Expect failed"; exit 1 }'
					)
				end
			elseif trimmed:find("%.toBeLessThan%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeLessThan%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if ("
							.. format_ps1_val(act)
							.. " -ge "
							.. format_ps1_val(num)
							.. ') { Write-Error "Expect failed"; exit 1 }'
					)
				end
			elseif trimmed:find("%.toBeLessThanOrEqual%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeLessThanOrEqual%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if ("
							.. format_ps1_val(act)
							.. " -gt "
							.. format_ps1_val(num)
							.. ') { Write-Error "Expect failed"; exit 1 }'
					)
				end
			elseif trimmed:find("%.toThrow") then
				local fn = trimmed:match("expect%s*%((.-)%)%..-toThrow")
				if fn then
					table.insert(
						lines,
						indent
							.. "try { "
							.. format_ps1_val(fn)
							.. '; Write-Error "Expect failed: expected error"; exit 1 } catch {}'
					)
				end
			end

		elseif
			trimmed:match("^function%s+([%w_]+)%s*%((.*)%)")
			or trimmed:match("^local%s+function%s+([%w_]+)%s*%((.*)%)")
			or trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)")
		then
			local fn_name, params_str
			if trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)") then
				fn_name = trimmed:match("^local%s+([%a_][%w_]*)%s*=") or trimmed:match("^([%a_][%w_]*)%s*=") or "co_fn"
				params_str = trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)")
			else
				fn_name, params_str = trimmed:match("function%s+([%w_]+)%s*%((.*)%)")
			end
			local ps_params = {}
			for param in (params_str or ""):gmatch("[^,]+") do
				param = param:match("^%s*(.-)%s*$")
				if param ~= "" then
					table.insert(ps_params, "$" .. param)
				end
			end
			table.insert(lines, indent .. "function " .. fn_name .. "(" .. table.concat(ps_params, ", ") .. ") {")

		elseif trimmed:match("^return%s*(.*)$") then
			local ret_expr = trimmed:match("^return%s*(.*)$"):match("^%s*(.-)%s*$")
			if ret_expr ~= "" then
				local fn1, a1, op, fn2, a2 = ret_expr:match("^([%a_][%w_]*)%((.*)%)%s*([+%*%/%-])%s*([%a_][%w_]*)%((.*)%)$")
				if fn1 and a1 and op and fn2 and a2 then
					table.insert(
						lines,
						indent
							.. "return ("
							.. fn1
							.. " ("
							.. to_ps1_expr(a1)
							.. ")) "
							.. op
							.. " ("
							.. fn2
							.. " ("
							.. to_ps1_expr(a2)
							.. "))"
					)
				else
					table.insert(lines, indent .. "return " .. format_ps1_val(ret_expr))
				end
			else
				table.insert(lines, indent .. "return")
			end

		elseif trimmed:match("^coroutine%.yield%((.*)%)") then
			local args = trimmed:match("^coroutine%.yield%((.*)%)")
			local parts = {}
			for _, part in ipairs(split_args(args)) do
				table.insert(parts, format_ps1_val(part))
			end
			table.insert(lines, indent .. "Write-Output " .. table.concat(parts, " "))

		elseif trimmed:match("^local%s+([%a_][%w_]*)%s*,%s*([%a_][%w_]*)%s*=%s*(.-)%((.*)%)") then
			local var_ok, var_res, fn_call, fn_args =
				trimmed:match("^local%s+([%a_][%w_]*)%s*,%s*([%a_][%w_]*)%s*=%s*(.-)%((.*)%)")
			fn_call = fn_call:match("^%s*(.-)%s*$")
			if fn_call == "coroutine.resume" then
				local args_parts = split_args(fn_args)
				local co_name = args_parts[1] or "co"
				local extra_args = {}
				for i = 2, #args_parts do
					table.insert(extra_args, format_ps1_val(args_parts[i]))
				end
				table.insert(
					lines,
					indent .. "$" .. var_res .. " = (" .. co_name .. " " .. table.concat(extra_args, " ") .. ")"
				)
				table.insert(lines, indent .. "$" .. var_ok .. " = $true")
			elseif fn_call == "pcall" then
				local args_parts = split_args(fn_args)
				local target_fn = args_parts[1] or "fn"
				local extra_args = {}
				for i = 2, #args_parts do
					table.insert(extra_args, format_ps1_val(args_parts[i]))
				end
				table.insert(lines, indent .. "try {")
				table.insert(lines, indent .. "  $" .. var_res .. " = " .. target_fn .. " " .. table.concat(extra_args, " "))
				table.insert(lines, indent .. "  $" .. var_ok .. " = $true")
				table.insert(lines, indent .. "} catch {")
				table.insert(lines, indent .. "  $" .. var_ok .. " = $false")
				table.insert(lines, indent .. "}")
			end

		elseif trimmed:match("^print%((.*)%)") then
			local args = trimmed:match("^print%((.*)%)")
			local parts = {}
			for _, part in ipairs(split_args(args)) do
				table.insert(parts, format_ps1_val(part))
			end
			table.insert(lines, indent .. "Write-Host " .. table.concat(parts, " "))

		elseif trimmed:match("^console%.[%w_]+%((.*)%)%s*$") then
			local args = trimmed:match("^console%.[%w_]+%((.*)%)%s*$")
			local parts = {}
			for _, raw in ipairs(split_args(args)) do
				if raw:sub(1, 1) == "{" then
					table.insert(parts, lua_tbl_to_ps1(raw))
				else
					table.insert(parts, format_ps1_val(raw))
				end
			end
			table.insert(lines, indent .. "Write-Host " .. table.concat(parts, " "))

		elseif trimmed:match("^error%((.*)%)") then
			local err_msg = trimmed:match("^error%((.*)%)")
			table.insert(lines, indent .. "throw " .. format_ps1_val(err_msg))

		elseif trimmed:match("^assert%((.*)%)") then
			local args = split_args(trimmed:match("^assert%((.*)%)"))
			local cond = args[1] or "true"
			local msg = args[2] or '"Assertion failed"'
			table.insert(lines, indent .. "if (-not (" .. to_ps1_expr(cond) .. ")) { throw " .. format_ps1_val(msg) .. " }")

		elseif trimmed:match("^fs%.mkdir%((.*)%)") then
			local path_arg = trimmed:match("^fs%.mkdir%((.*)%)")
			table.insert(
				lines,
				indent .. "New-Item -ItemType Directory -Force -Path " .. format_ps1_val(path_arg) .. " | Out-Null"
			)

		elseif trimmed:match("^fs%.write%((.*)%)") then
			local args = split_args(trimmed:match("^fs%.write%((.*)%)"))
			local path_arg = args[1]
			local content_arg = args[2] or '""'
			table.insert(
				lines,
				indent .. "Set-Content -Path " .. format_ps1_val(path_arg) .. " -Value " .. format_ps1_val(content_arg)
			)

		elseif trimmed:match("^fs%.remove%((.*)%)") or trimmed:match("^fs%.delete%((.*)%)") then
			local path_arg = trimmed:match("%((.*)%)")
			table.insert(lines, indent .. "Remove-Item -Recurse -Force -Path " .. format_ps1_val(path_arg))

		elseif
			trimmed:match("^%s*%$%s*%((.*)%)")
			or trimmed:match("^%s*terminal%.exec%((.*)%)")
			or trimmed:match("^%s*terminal%.run%((.*)%)")
		then
			local cmd_arg = trimmed:match("%((.*)%)")
			cmd_arg = cmd_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			table.insert(lines, indent .. cmd_arg)

		elseif trimmed:match("^local%s+[%a_][%w_]*%s*=%s*") or trimmed:match("^[%a_][%w_]*%s*=%s*") then
			local is_local, var, val
			if trimmed:match("^local%s+") then
				var, val = trimmed:match("^local%s+([%a_][%w_]*)%s*=%s*(.*)$")
				is_local = true
			else
				var, val = trimmed:match("^([%a_][%w_]*)%s*=%s*(.*)$")
				is_local = false
			end

			if val:sub(1, 1) == "{" and val:sub(-1) == "}" then
				table.insert(lines, indent .. "$" .. var .. " = " .. lua_tbl_to_ps1(val))

			elseif val:match("^fs%.read%((.*)%)") then
				local path_arg = val:match("^fs%.read%((.*)%)")
				table.insert(lines, indent .. "$" .. var .. " = Get-Content -Raw " .. format_ps1_val(path_arg))

			elseif val:match("^json%.encode%((.*)%)") then
				local obj_arg = val:match("^json%.encode%((.*)%)")
				local ps1_obj = obj_arg:sub(1, 1) == "{" and lua_tbl_to_ps1(obj_arg) or format_ps1_val(obj_arg)
				table.insert(lines, indent .. "$" .. var .. " = (" .. ps1_obj .. " | ConvertTo-Json -Compress)")

			elseif val:match("^json%.load%((.*)%)") then
				local path_arg = val:match("^json%.load%((.*)%)")
				table.insert(
					lines,
					indent .. "$" .. var .. " = (Get-Content -Raw " .. format_ps1_val(path_arg) .. " | ConvertFrom-Json)"
				)

			elseif val:match("^fetch%.get%((.*)%)") then
				local url_arg = val:match("^fetch%.get%((.*)%)")
				table.insert(
					lines,
					indent
						.. "$"
						.. var
						.. " = (Invoke-WebRequest -Uri "
						.. format_ps1_val(url_arg)
						.. " -UseBasicParsing).Content"
				)

			elseif val:match("^fetch%.json%((.*)%)") then
				local url_arg = val:match("^fetch%.json%((.*)%)")
				table.insert(lines, indent .. "$" .. var .. " = Invoke-RestMethod -Uri " .. format_ps1_val(url_arg))

			elseif val:match("^terminal%..-%((.*)%)") or val:match("^%s*%$%s*%((.*)%)") then
				local cmd_arg = val:match("%((.*)%)"):gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
				table.insert(lines, indent .. "$" .. var .. " = (" .. cmd_arg .. ")")

			elseif val:match("^[%a_][%w_]*%s*%((.*)%)") then
				local fn_name, fn_args = val:match("^([%a_][%w_]*)%s*%((.*)%)")
				if
					fn_name == "setTimeout"
					or fn_name == "setInterval"
					or fn_name == "clearTimeout"
					or fn_name == "clearInterval"
				then
					table.insert(lines, indent .. "$" .. var .. ' = "timer_id"')
				else
					local ps_args = {}
					for _, arg in ipairs(split_args(fn_args)) do
						table.insert(ps_args, format_ps1_val(arg))
					end
					table.insert(lines, indent .. "$" .. var .. " = (" .. fn_name .. " " .. table.concat(ps_args, " ") .. ")")
				end

			else
				table.insert(lines, indent .. "$" .. var .. " = " .. format_ps1_val(val))
			end

		elseif trimmed:match("^async%.sleep%s*%((.*)%)") or trimmed:match("^sleep%s*%((.*)%)") then
			local ms_arg = trimmed:match("^async%.sleep%s*%((.*)%)") or trimmed:match("^sleep%s*%((.*)%)")
			local ms_val = format_ps1_val(ms_arg)
			table.insert(lines, indent .. "Start-Sleep -Milliseconds " .. ms_val)

		elseif
			trimmed:match("^setTimeout%s*%(")
			or trimmed:match("^setInterval%s*%(")
			or trimmed:match("^clearTimeout%s*%(")
			or trimmed:match("^clearInterval%s*%(")
		then
			table.insert(lines, indent .. "# " .. trimmed)

		elseif trimmed:match("^async%..-%((.*)%)") then
			table.insert(lines, indent .. "# " .. trimmed)

		elseif trimmed:match("^dofile%s*%((.*)%)") or trimmed:match("^loadfile%s*%((.*)%)") then
			local file_arg = trimmed:match("^dofile%s*%((.*)%)") or trimmed:match("^loadfile%s*%((.*)%)")
			local clean_arg = file_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			if clean_arg:match("%.krsnvim$") then
				local ps_target = clean_arg:gsub("%.krsnvim$", ".ps1")
				table.insert(
					lines,
					indent
						.. 'if (Test-Path "'
						.. ps_target
						.. '") { pwsh -NoProfile -File "'
						.. ps_target
						.. '" } else { nvim -l "'
						.. clean_arg
						.. '" }'
				)
			else
				table.insert(lines, indent .. 'nvim -l "' .. clean_arg .. '"')
			end

		elseif trimmed:match("^os%.exit%s*%((.*)%)") then
			local code_arg = trimmed:match("^os%.exit%s*%((.*)%)") or "0"
			table.insert(lines, indent .. "exit " .. format_ps1_val(code_arg))

		elseif trimmed:match("^os%.execute%s*%((.*)%)") then
			local cmd_arg = trimmed:match("^os%.execute%s*%((.*)%)")
			local clean_cmd = cmd_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			table.insert(lines, indent .. clean_cmd)

		elseif trimmed:match("^os%.remove%s*%((.*)%)") then
			local path_arg = trimmed:match("^os%.remove%s*%((.*)%)")
			table.insert(lines, indent .. "Remove-Item -Force " .. format_ps1_val(path_arg))

		elseif trimmed:match("^[%a_][%w_%.%:]*%s*%((.*)%)%s*$") then
			local fn_name, fn_args = trimmed:match("^([%a_][%w_%.%:]*)%s*%((.*)%)%s*$")
			if
				fn_name == "setTimeout"
				or fn_name == "setInterval"
				or fn_name == "clearTimeout"
				or fn_name == "clearInterval"
			then
				table.insert(lines, indent .. "# " .. trimmed)
			elseif fn_name:sub(1, 6) == "async." or fn_name:sub(1, 8) == "coroutine" then
				table.insert(lines, indent .. "# " .. trimmed)
			else
				local ps_args = {}
				for _, arg in ipairs(split_args(fn_args)) do
					table.insert(ps_args, format_ps1_val(arg))
				end
				if fn_name:find("%.") or fn_name:find(":") then
					local ps_target = "$" .. fn_name:gsub(":", ".")
					table.insert(lines, indent .. ps_target .. "(" .. table.concat(ps_args, ", ") .. ")")
				else
					table.insert(lines, indent .. fn_name .. " " .. table.concat(ps_args, " "))
				end
			end

		elseif
			trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s+do$")
			or trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$")
		then
			local var, start_val, stop_val, step_val
			if trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$") then
				var, start_val, stop_val, step_val =
					trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$")
			else
				var, start_val, stop_val = trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s+do$")
				step_val = "1"
			end
			table.insert(
				lines,
				indent
					.. "for ($"
					.. var
					.. " = "
					.. format_ps1_val(start_val)
					.. "; $"
					.. var
					.. " -le "
					.. format_ps1_val(stop_val)
					.. "; $"
					.. var
					.. " += "
					.. format_ps1_val(step_val)
					.. ") {"
			)

		elseif trimmed:match("^for%s+[%w_]+%s*,%s*([%a_][%w_]*)%s+in%s+ipairs%(([%a_][%w_]*)%)%s+do$") then
			local item_var, list_var = trimmed:match("^for%s+[%w_]+%s*,%s*([%a_][%w_]*)%s+in%s+ipairs%(([%a_][%w_]*)%)%s+do$")
			table.insert(lines, indent .. "foreach ($" .. item_var .. " in $" .. list_var .. ") {")

		elseif trimmed:match("^while%s+(.-)%s+do$") then
			local cond = trimmed:match("^while%s+(.-)%s+do$")
			table.insert(lines, indent .. "while (" .. to_ps1_expr(cond) .. ") {")

		elseif trimmed:match("^if%s+(.-)%s+then$") then
			local cond = trimmed:match("^if%s+(.-)%s+then$")
			if cond:match("^not%s+fs%.exists%((.*)%)") then
				local p = cond:match("^not%s+fs%.exists%((.*)%)")
				table.insert(lines, indent .. "if (-not (Test-Path " .. format_ps1_val(p) .. ")) {")
			elseif cond:match("^fs%.exists%((.*)%)") then
				local p = cond:match("^fs%.exists%((.*)%)")
				table.insert(lines, indent .. "if (Test-Path " .. format_ps1_val(p) .. ") {")
			else
				table.insert(lines, indent .. "if (" .. to_ps1_expr(cond) .. ") {")
			end

		elseif trimmed:match("^elseif%s+(.-)%s+then$") then
			local cond = trimmed:match("^elseif%s+(.-)%s+then$")
			if cond:match("^not%s+fs%.exists%((.*)%)") then
				local p = cond:match("^not%s+fs%.exists%((.*)%)")
				table.insert(lines, indent .. "} elseif (-not (Test-Path " .. format_ps1_val(p) .. ")) {")
			elseif cond:match("^fs%.exists%((.*)%)") then
				local p = cond:match("^fs%.exists%((.*)%)")
				table.insert(lines, indent .. "} elseif (Test-Path " .. format_ps1_val(p) .. ") {")
			else
				table.insert(lines, indent .. "} elseif (" .. to_ps1_expr(cond) .. ") {")
			end

		elseif trimmed == "else" then
			table.insert(lines, indent .. "} else {")

		elseif trimmed == "end" or trimmed:match("^end%)?") or trimmed == "}" then
			local last_block = table.remove(block_stack)
			if last_block ~= "noop" then
				table.insert(lines, indent .. "}")
			end
		else
			local l = line:gsub("^%s*%-%-", indent .. "#")
			table.insert(lines, l)
		end
	end

	return table.concat(lines, "\n")
end

return M
