-- ============================================================================
-- KRSNVIMSCRIPT TRANSPILER -- POSIX Shell (.sh) Generator
-- ============================================================================

local common = require("krs.lib.krsnvim.krsnvimtranspiler.common")

local M = {}

local LUA_KEYWORDS = common.LUA_KEYWORDS
local join_multiline_calls = common.join_multiline_calls
local format_sh_val = common.format_sh_val
local lua_tbl_to_json = common.lua_tbl_to_json
local format_sh_cond = common.format_sh_cond
local split_args = common.split_args

--- Transpiles `.krsnvim` Lua code string into Bash script (`.sh`).
--- @param code string Full Lua code string of a .krsnvim script.
--- @return string bash_script Equivalent Bash script.
function M.to_sh(code)
	local lines = {}
	table.insert(lines, "#!/usr/bin/env bash")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "# Transpiled from krsnvimscript (.krsnvim) -> Bash (.sh)")
	table.insert(lines, "# Automatically generated by krsnvimtranspiler")
	table.insert(lines, "# ==========================================================================")
	table.insert(lines, "set -e")
	table.insert(lines, "")

	local block_stack = {}

	for line in join_multiline_calls(code):gmatch("[^\r\n]+") do
		local trimmed = line:match("^%s*(.-)%s*$")
		local indent = line:match("^(%s*)") or ""

		-- Skip or comment out require/import lines
		if
			trimmed:match("^local%s+[%w_]+%s*=%s*require%(")
			or trimmed:match("^local%s+[%w_]+%s*=%s*import%(")
			or trimmed:match("^require%(")
			or trimmed:match("^import%(")
		then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed .. " (mapped to native CLI tools)")

		-- Comments: -- comment -> # comment
		elseif trimmed:sub(1, 2) == "--" then
			local comment_text = trimmed:sub(3):match("^%s*(.-)%s*$")
			table.insert(lines, indent .. "# " .. comment_text)

		-- Empty lines
		elseif trimmed == "" then
			table.insert(lines, "")

		-- Testing Framework Hooks: test.beforeAll, test.afterAll, test.beforeEach, test.afterEach, etc.
		elseif
			trimmed:match("^[%w_]*%.?beforeAll%s*%(")
			or trimmed:match("^[%w_]*%.?afterAll%s*%(")
			or trimmed:match("^[%w_]*%.?beforeEach%s*%(")
			or trimmed:match("^[%w_]*%.?afterEach%s*%(")
		then
			table.insert(block_stack, "noop")

		-- Testing Framework Suites: describe("suite", function() ...) or test.describe(...)
		elseif trimmed:match("^describe%s*%(") or trimmed:match("^[%w_]+%.describe%s*%(") then
			local suite_name = trimmed:match('describe%s*%("%s*(.-)%s*"')
				or trimmed:match("describe%s*%('%s*(.-)%s*'")
				or "Test Suite"
			table.insert(block_stack, "noop")
			table.insert(lines, indent .. 'echo "📦 Suite: ' .. suite_name .. '"')

		-- Testing Framework Runner: test.run() or t.run() or run()
		elseif trimmed:match("^[%w_]+%.run%s*%(") or trimmed:match("^run%s*%(") then
			table.insert(lines, indent .. "# [krsnvim] " .. trimmed)

		-- Testing Framework Tests: it("test", function() ...) or test("test", function() ...) or test.test(...)
		elseif
			trimmed:match("^it%s*%(")
			or trimmed:match("^test%s*%(")
			or trimmed:match("^[%w_]+%.it%s*%(")
			or trimmed:match("^[%w_]+%.test%s*%(")
		then
			local test_name = trimmed:match('it%s*%("%s*(.-)%s*"')
				or trimmed:match('test%s*%("%s*(.-)%s*"')
				or trimmed:match("it%s*%('%s*(.-)%s*'")
				or trimmed:match("test%s*%('%s*(.-)%s*'")
				or "Test"
			table.insert(block_stack, "noop")
			table.insert(lines, indent .. 'echo "  ✓ ' .. test_name .. '"')

		-- Testing Framework Assertions: expect(val)...
		elseif trimmed:match("^expect%s*%(") then
			local is_inv = trimmed:find("%.isNot%.")
				or trimmed:find('%["not"%]')
				or trimmed:find("%.not%.")
				or trimmed:find("%.not_%.")

			if trimmed:find("%.toBe%s*%(") or trimmed:find("%.toEqual%s*%(") then
				local act, exp = trimmed:match("expect%s*%((.-)%)%..-toBe%s*%((.-)%)")
				if not act then
					act, exp = trimmed:match("expect%s*%((.-)%)%..-toEqual%s*%((.-)%)")
				end
				if act and exp then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if [ "
								.. format_sh_val(act)
								.. " == "
								.. format_sh_val(exp)
								.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent
								.. "if [ "
								.. format_sh_val(act)
								.. " != "
								.. format_sh_val(exp)
								.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toBeTruthy%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if [ -n "
								.. format_sh_val(act)
								.. " ] && [ "
								.. format_sh_val(act)
								.. ' != "false" ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent
								.. "if [ -z "
								.. format_sh_val(act)
								.. " ] || [ "
								.. format_sh_val(act)
								.. ' == "false" ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toBeFalsy%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if [ -z "
								.. format_sh_val(act)
								.. " ] || [ "
								.. format_sh_val(act)
								.. ' == "false" ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent
								.. "if [ -n "
								.. format_sh_val(act)
								.. " ] && [ "
								.. format_sh_val(act)
								.. ' != "false" ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif
				trimmed:find("%.toBeNil%s*%(")
				or trimmed:find("%.toBeNull%s*%(")
				or trimmed:find("%.toBeUndefined%s*%(")
			then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent .. "if [ -z " .. format_sh_val(act) .. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent .. "if [ -n " .. format_sh_val(act) .. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toBeDefined%s*%(") then
				local act = trimmed:match("expect%s*%((.-)%)%.")
				if act then
					if is_inv then
						table.insert(
							lines,
							indent .. "if [ -n " .. format_sh_val(act) .. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent .. "if [ -z " .. format_sh_val(act) .. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toContain%s*%(") then
				local act, item = trimmed:match("expect%s*%((.-)%)%..-toContain%s*%((.-)%)")
				if act and item then
					local clean_item = item:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if [[ "
								.. format_sh_val(act)
								.. " == *"
								.. clean_item
								.. '* ]]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent
								.. "if [[ "
								.. format_sh_val(act)
								.. " != *"
								.. clean_item
								.. '* ]]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toHaveLength%s*%(") then
				local act, len = trimmed:match("expect%s*%((.-)%)%..-toHaveLength%s*%((.-)%)")
				if act and len then
					if is_inv then
						table.insert(
							lines,
							indent
								.. "if [ ${#"
								.. act
								.. "} -eq "
								.. format_sh_val(len)
								.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					else
						table.insert(
							lines,
							indent
								.. "if [ ${#"
								.. act
								.. "} -ne "
								.. format_sh_val(len)
								.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
						)
					end
				end
			elseif trimmed:find("%.toBeGreaterThan%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeGreaterThan%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if [ "
							.. format_sh_val(act)
							.. " -le "
							.. format_sh_val(num)
							.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
					)
				end
			elseif trimmed:find("%.toBeGreaterThanOrEqual%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeGreaterThanOrEqual%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if [ "
							.. format_sh_val(act)
							.. " -lt "
							.. format_sh_val(num)
							.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
					)
				end
			elseif trimmed:find("%.toBeLessThan%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeLessThan%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if [ "
							.. format_sh_val(act)
							.. " -ge "
							.. format_sh_val(num)
							.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
					)
				end
			elseif trimmed:find("%.toBeLessThanOrEqual%s*%(") then
				local act, num = trimmed:match("expect%s*%((.-)%)%..-toBeLessThanOrEqual%s*%((.-)%)")
				if act and num then
					table.insert(
						lines,
						indent
							.. "if [ "
							.. format_sh_val(act)
							.. " -gt "
							.. format_sh_val(num)
							.. ' ]; then echo "❌ Expect failed"; exit 1; fi'
					)
				end
			elseif trimmed:find("%.toThrow") then
				local fn = trimmed:match("expect%s*%((.-)%)%..-toThrow")
				if fn then
					table.insert(
						lines,
						indent
							.. "if "
							.. format_sh_val(fn)
							.. ' 2>/dev/null; then echo "❌ Expect failed: expected error"; exit 1; fi'
					)
				end
			end

		-- Function definitions or Coroutine creation: function fn_name(arg1, arg2)
		elseif
			trimmed:match("^function%s+([%w_]+)%s*%((.*)%)")
			or trimmed:match("^local%s+function%s+([%w_]+)%s*%((.*)%)")
			or trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)")
		then
			local fn_name, params_str
			if trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)") then
				fn_name = trimmed:match("^local%s+([%a_][%w_]*)%s*=") or trimmed:match("^([%a_][%w_]*)%s*=") or "co_fn"
				params_str = trimmed:match("coroutine%..-%(%s*function%s*%((.*)%)")
			else
				fn_name, params_str = trimmed:match("function%s+([%w_]+)%s*%((.*)%)")
			end
			table.insert(block_stack, "function")
			table.insert(lines, indent .. fn_name .. "() {")
			local idx = 1
			for param in (params_str or ""):gmatch("[^,]+") do
				param = param:match("^%s*(.-)%s*$")
				if param ~= "" then
					table.insert(lines, indent .. '  local ' .. param .. '="$' .. idx .. '"')
					idx = idx + 1
				end
			end

		-- Return statements: return expr
		elseif trimmed:match("^return%s*(.*)$") then
			local ret_expr = trimmed:match("^return%s*(.*)$"):match("^%s*(.-)%s*$")
			if ret_expr ~= "" then
				local fn1, a1, op, fn2, a2 = ret_expr:match("^([%a_][%w_]*)%((.*)%)%s*([+%*%/%-])%s*([%a_][%w_]*)%((.*)%)$")
				if fn1 and a1 and op and fn2 and a2 then
					local arith1 = a1:gsub("([%a_][%w_]*)", function(w)
						return w
					end)
					local arith2 = a2:gsub("([%a_][%w_]*)", function(w)
						return w
					end)
					table.insert(
						lines,
						indent
							.. "echo $(( $("
							.. fn1
							.. " $(( "
							.. arith1
							.. " ))) "
							.. op
							.. " $("
							.. fn2
							.. " $(( "
							.. arith2
							.. " ))) ))"
					)
				else
					table.insert(lines, indent .. "echo " .. format_sh_val(ret_expr))
				end
			end
			table.insert(lines, indent .. "return 0")

		-- coroutine.yield(...) -> echo ...
		elseif trimmed:match("^coroutine%.yield%((.*)%)") then
			local args = trimmed:match("^coroutine%.yield%((.*)%)")
			local echoed = {}
			for _, arg in ipairs(split_args(args)) do
				table.insert(echoed, format_sh_val(arg))
			end
			table.insert(lines, indent .. "echo " .. table.concat(echoed, " "))

		-- Multiple variable assignment: local ok, val = coroutine.resume(co, arg) OR pcall(fn, arg)
		elseif trimmed:match("^local%s+([%a_][%w_]*)%s*,%s*([%a_][%w_]*)%s*=%s*(.-)%((.*)%)") then
			local var_ok, var_res, fn_call, fn_args =
				trimmed:match("^local%s+([%a_][%w_]*)%s*,%s*([%a_][%w_]*)%s*=%s*(.-)%((.*)%)")
			fn_call = fn_call:match("^%s*(.-)%s*$")
			if fn_call == "coroutine.resume" then
				local args_parts = split_args(fn_args)
				local co_name = args_parts[1] or "co"
				local extra_args = {}
				for i = 2, #args_parts do
					table.insert(extra_args, format_sh_val(args_parts[i]))
				end
				table.insert(lines, indent .. var_res .. "=$(" .. co_name .. " " .. table.concat(extra_args, " ") .. ")")
				table.insert(lines, indent .. var_ok .. '="true"')
			elseif fn_call == "pcall" then
				local args_parts = split_args(fn_args)
				local target_fn = args_parts[1] or "fn"
				local extra_args = {}
				for i = 2, #args_parts do
					table.insert(extra_args, format_sh_val(args_parts[i]))
				end
				table.insert(
					lines,
					indent
						.. "if "
						.. var_res
						.. "=$("
						.. target_fn
						.. " "
						.. table.concat(extra_args, " ")
						.. " 2>/dev/null); then"
				)
				table.insert(lines, indent .. "  " .. var_ok .. '="true"')
				table.insert(lines, indent .. "else")
				table.insert(lines, indent .. "  " .. var_ok .. '="false"')
				table.insert(lines, indent .. "fi")
			end

		-- print(...) -> echo ...
		elseif trimmed:match("^print%((.*)%)") then
			local args = trimmed:match("^print%((.*)%)")
			local echoed = {}
			for _, arg in ipairs(split_args(args)) do
				table.insert(echoed, format_sh_val(arg))
			end
			table.insert(lines, indent .. "echo " .. table.concat(echoed, " "))

		-- console.log(...) / console.info(...) -> echo ...
		elseif trimmed:match("^console%.[%w_]+%((.*)%)%s*$") then
			local args = trimmed:match("^console%.[%w_]+%((.*)%)%s*$")
			local echoed = {}
			for _, raw in ipairs(split_args(args)) do
				if raw:sub(1, 1) == "{" then
					table.insert(echoed, lua_tbl_to_json(raw))
				else
					table.insert(echoed, format_sh_val(raw))
				end
			end
			table.insert(lines, indent .. "echo " .. table.concat(echoed, " "))

		-- error(msg) -> echo "msg" >&2; exit 1
		elseif trimmed:match("^error%((.*)%)") then
			local err_msg = trimmed:match("^error%((.*)%)")
			table.insert(lines, indent .. "echo " .. format_sh_val(err_msg) .. " >&2")
			table.insert(lines, indent .. "exit 1")

		-- assert(cond, msg) -> [[ cond ]] || { echo "msg" >&2; exit 1; }
		elseif trimmed:match("^assert%((.*)%)") then
			local args = split_args(trimmed:match("^assert%((.*)%)"))
			local cond = args[1] or "true"
			local msg = args[2] or '"Assertion failed"'
			local mode, cond_str = format_sh_cond(cond)
			if mode == "arithmetic" then
				table.insert(lines, indent .. "(( " .. cond_str .. " )) || { echo " .. format_sh_val(msg) .. " >&2; exit 1; }")
			else
				table.insert(lines, indent .. "[[ " .. cond_str .. " ]] || { echo " .. format_sh_val(msg) .. " >&2; exit 1; }")
			end

		-- fs.mkdir(path) -> mkdir -p path
		elseif trimmed:match("^fs%.mkdir%((.*)%)") then
			local path_arg = trimmed:match("^fs%.mkdir%((.*)%)")
			table.insert(lines, indent .. "mkdir -p " .. format_sh_val(path_arg))

		-- fs.write(path, content) -> echo content > path
		elseif trimmed:match("^fs%.write%((.*)%)") then
			local args = split_args(trimmed:match("^fs%.write%((.*)%)"))
			local path_arg = args[1]
			local content_arg = args[2] or '""'
			table.insert(lines, indent .. "echo " .. format_sh_val(content_arg) .. " > " .. format_sh_val(path_arg))

		-- fs.append(path, content) -> echo content >> path
		elseif trimmed:match("^fs%.append%((.*)%)") then
			local args = split_args(trimmed:match("^fs%.append%((.*)%)"))
			local path_arg = args[1]
			local content_arg = args[2] or '""'
			table.insert(lines, indent .. "echo " .. format_sh_val(content_arg) .. " >> " .. format_sh_val(path_arg))

		-- fs.remove(path) / fs.delete(path) -> rm -rf path
		elseif trimmed:match("^fs%.remove%((.*)%)") or trimmed:match("^fs%.delete%((.*)%)") then
			local path_arg = trimmed:match("%((.*)%)")
			table.insert(lines, indent .. "rm -rf " .. format_sh_val(path_arg))

		-- $ "cmd" or terminal.exec("cmd") -> cmd
		elseif
			trimmed:match("^%s*%$%s*%((.*)%)")
			or trimmed:match("^%s*terminal%.exec%((.*)%)")
			or trimmed:match("^%s*terminal%.run%((.*)%)")
		then
			local cmd_arg = trimmed:match("%((.*)%)")
			cmd_arg = cmd_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			table.insert(lines, indent .. cmd_arg)

		-- Variable assignments: local var = val OR var = val
		elseif trimmed:match("^local%s+[%a_][%w_]*%s*=%s*") or trimmed:match("^[%a_][%w_]*%s*=%s*") then
			local is_local, var, val
			if trimmed:match("^local%s+") then
				var, val = trimmed:match("^local%s+([%a_][%w_]*)%s*=%s*(.*)$")
				is_local = true
			else
				var, val = trimmed:match("^([%a_][%w_]*)%s*=%s*(.*)$")
				is_local = false
			end

			local prefix = is_local and "local " or ""

			-- Table/array literal: local list = { "a", "b" }
			if val:sub(1, 1) == "{" and val:sub(-1) == "}" then
				local s = val:match("^%s*{?(.-)}?%s*$")
				local args = split_args(s)
				local items = {}
				for _, item in ipairs(args) do
					table.insert(items, format_sh_val(item))
				end
				table.insert(lines, indent .. prefix .. var .. "=(" .. table.concat(items, " ") .. ")")

			-- Builtin: fs.read(path) -> cat path
			elseif val:match("^fs%.read%((.*)%)") then
				local path_arg = val:match("^fs%.read%((.*)%)")
				table.insert(lines, indent .. prefix .. var .. "=$(cat " .. format_sh_val(path_arg) .. ")")

			-- Builtin: json.encode(obj) -> echo obj | jq -c .
			elseif val:match("^json%.encode%((.*)%)") then
				local obj_arg = val:match("^json%.encode%((.*)%)")
				local json_str = obj_arg:sub(1, 1) == "{" and lua_tbl_to_json(obj_arg) or format_sh_val(obj_arg)
				table.insert(
					lines,
					indent
						.. prefix
						.. var
						.. '=$(echo '
						.. json_str
						.. ' | (python3 -c "import sys, json; print(json.dumps(json.load(sys.stdin)))" 2>/dev/null || jq -c .))'
				)

			-- Builtin: json.load(path) -> cat path
			elseif val:match("^json%.load%((.*)%)") then
				local path_arg = val:match("^json%.load%((.*)%)")
				table.insert(lines, indent .. prefix .. var .. "=$(cat " .. format_sh_val(path_arg) .. ")")

			-- Builtin: fetch.get(url) -> curl -sSL url
			elseif val:match("^fetch%.get%((.*)%)") then
				local url_arg = val:match("^fetch%.get%((.*)%)")
				table.insert(lines, indent .. prefix .. var .. "=$(curl -sSL " .. format_sh_val(url_arg) .. ")")

			-- Builtin: fetch.json(url) -> curl -sSL url
			elseif val:match("^fetch%.json%((.*)%)") then
				local url_arg = val:match("^fetch%.json%((.*)%)")
				table.insert(lines, indent .. prefix .. var .. "=$(curl -sSL " .. format_sh_val(url_arg) .. ")")

			-- Builtin: terminal execution
			elseif val:match("^terminal%..-%((.*)%)") or val:match("^%s*%$%s*%((.*)%)") then
				local cmd_arg = val:match("%((.*)%)"):gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
				table.insert(lines, indent .. prefix .. var .. "=$(" .. cmd_arg .. ")")

			-- Custom function call: var = fn(a, b)
			elseif val:match("^[%a_][%w_]*%s*%((.*)%)") then
				local fn_name, fn_args = val:match("^([%a_][%w_]*)" .. "%s*%((.*)%)")
				if
					fn_name == "setTimeout"
					or fn_name == "setInterval"
					or fn_name == "clearTimeout"
					or fn_name == "clearInterval"
				then
					table.insert(lines, indent .. prefix .. var .. '="timer_id"')
				else
					local sh_args = {}
					for _, arg in ipairs(split_args(fn_args)) do
						table.insert(sh_args, format_sh_val(arg))
					end
					table.insert(lines, indent .. prefix .. var .. "=$(" .. fn_name .. " " .. table.concat(sh_args, " ") .. ")")
				end

			-- Standard value / math assignment
			else
				table.insert(lines, indent .. prefix .. var .. "=" .. format_sh_val(val))
			end

		-- Builtin: async.sleep(ms) / sleep(ms) -> sleep in seconds via python3 or sleep 1
		elseif trimmed:match("^async%.sleep%s*%((.*)%)") or trimmed:match("^sleep%s*%((.*)%)") then
			local ms_arg = trimmed:match("^async%.sleep%s*%((.*)%)") or trimmed:match("^sleep%s*%((.*)%)")
			local ms_val = format_sh_val(ms_arg)
			table.insert(
				lines,
				indent .. 'python3 -c "import time; time.sleep(' .. ms_val .. '/1000)" 2>/dev/null || sleep 1'
			)

		-- Builtin: JS-style Timers (setTimeout, setInterval, clearTimeout, clearInterval)
		elseif
			trimmed:match("^setTimeout%s*%(")
			or trimmed:match("^setInterval%s*%(")
			or trimmed:match("^clearTimeout%s*%(")
			or trimmed:match("^clearInterval%s*%(")
		then
			table.insert(lines, indent .. "# " .. trimmed)

		-- Builtin: async channel & coroutine / task calls
		elseif trimmed:match("^async%..-%((.*)%)") then
			table.insert(lines, indent .. "# " .. trimmed)

		-- Builtin: dofile(path) / loadfile(path) -> nvim -l path or bash path.sh
		elseif trimmed:match("^dofile%s*%((.*)%)") or trimmed:match("^loadfile%s*%((.*)%)") then
			local file_arg = trimmed:match("^dofile%s*%((.*)%)") or trimmed:match("^loadfile%s*%((.*)%)")
			local clean_arg = file_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			if clean_arg:match("%.krsnvim$") then
				local sh_target = clean_arg:gsub("%.krsnvim$", ".sh")
				table.insert(lines, indent .. 'bash "' .. sh_target .. '" 2>/dev/null || nvim -l "' .. clean_arg .. '"')
			else
				table.insert(lines, indent .. 'nvim -l "' .. clean_arg .. '" 2>/dev/null || lua "' .. clean_arg .. '"')
			end

		-- Builtin: os.exit(code)
		elseif trimmed:match("^os%.exit%s*%((.*)%)") then
			local code_arg = trimmed:match("^os%.exit%s*%((.*)%)") or "0"
			table.insert(lines, indent .. "exit " .. format_sh_val(code_arg))

		-- Builtin: os.execute(cmd)
		elseif trimmed:match("^os%.execute%s*%((.*)%)") then
			local cmd_arg = trimmed:match("^os%.execute%s*%((.*)%)")
			local clean_cmd = cmd_arg:gsub('^"', ""):gsub('"$', ""):gsub("^'", ""):gsub("'$", "")
			table.insert(lines, indent .. clean_cmd)

		-- Builtin: os.remove(path)
		elseif trimmed:match("^os%.remove%s*%((.*)%)") then
			local path_arg = trimmed:match("^os%.remove%s*%((.*)%)")
			table.insert(lines, indent .. "rm -f " .. format_sh_val(path_arg))

		-- Custom standalone function calls or method calls: fn(arg1, arg2) or obj.fn(arg1, arg2) or obj:fn(arg1, arg2)
		elseif trimmed:match("^[%a_][%w_%.%:]*%s*%((.*)%)%s*$") then
			local fn_name, fn_args = trimmed:match("^([%a_][%w_%.%:]*)%s*%((.*)%)%s*$")
			if
				fn_name == "setTimeout"
				or fn_name == "setInterval"
				or fn_name == "clearTimeout"
				or fn_name == "clearInterval"
			then
				table.insert(lines, indent .. "# " .. trimmed)
			elseif fn_name:sub(1, 6) == "async." or fn_name:sub(1, 8) == "coroutine" then
				table.insert(lines, indent .. "# " .. trimmed)
			else
				local sh_args = {}
				for _, arg in ipairs(split_args(fn_args)) do
					table.insert(sh_args, format_sh_val(arg))
				end
				local safe_fn = fn_name:gsub("[%.:]", "_")
				table.insert(lines, indent .. safe_fn .. " " .. table.concat(sh_args, " "))
			end

		-- Loops: for i = start, stop do OR for i = start, stop, step do
		elseif
			trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s+do$")
			or trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$")
		then
			local var, start_val, stop_val, step_val
			if trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$") then
				var, start_val, stop_val, step_val =
					trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s*,%s*(.-)%s+do$")
			else
				var, start_val, stop_val = trimmed:match("^for%s+([%a_][%w_]*)%s*=%s*(.-)%s*,%s*(.-)%s+do$")
				step_val = "1"
			end
			table.insert(block_stack, "for")
			table.insert(
				lines,
				indent
					.. "for (("
					.. var
					.. "="
					.. start_val
					.. "; "
					.. var
					.. "<="
					.. stop_val
					.. "; "
					.. var
					.. "+="
					.. step_val
					.. ")); do"
			)

		-- Loops: for _, item in ipairs(list) do
		elseif trimmed:match("^for%s+[%w_]+%s*,%s*([%a_][%w_]*)%s+in%s+ipairs%(([%a_][%w_]*)%)%s+do$") then
			local item_var, list_var = trimmed:match("^for%s+[%w_]+%s*,%s*([%a_][%w_]*)%s+in%s+ipairs%(([%a_][%w_]*)%)%s+do$")
			table.insert(block_stack, "for")
			table.insert(lines, indent .. 'for ' .. item_var .. ' in "${' .. list_var .. '[@]}"; do')

		-- Loops: while cond do
		elseif trimmed:match("^while%s+(.-)%s+do$") then
			local cond = trimmed:match("^while%s+(.-)%s+do$")
			table.insert(block_stack, "while")
			local mode, expr = format_sh_cond(cond)
			if mode == "arithmetic" then
				table.insert(lines, indent .. "while (( " .. expr .. " )); do")
			else
				table.insert(lines, indent .. "while [[ " .. expr .. " ]]; do")
			end

		-- Control Flow: if ... then
		elseif trimmed:match("^if%s+(.-)%s+then$") then
			local cond = trimmed:match("^if%s+(.-)%s+then$")
			table.insert(block_stack, "if")
			local mode, expr = format_sh_cond(cond)
			if mode == "arithmetic" then
				table.insert(lines, indent .. "if (( " .. expr .. " )); then")
			else
				table.insert(lines, indent .. "if [[ " .. expr .. " ]]; then")
			end

		-- Control Flow: elseif ... then
		elseif trimmed:match("^elseif%s+(.-)%s+then$") then
			local cond = trimmed:match("^elseif%s+(.-)%s+then$")
			local mode, expr = format_sh_cond(cond)
			if mode == "arithmetic" then
				table.insert(lines, indent .. "elif (( " .. expr .. " )); then")
			else
				table.insert(lines, indent .. "elif [[ " .. expr .. " ]]; then")
			end

		-- Control Flow: else
		elseif trimmed == "else" then
			table.insert(lines, indent .. "else")

		-- Block End: end or end)
		elseif trimmed == "end" or trimmed:match("^end%)?") or trimmed == "}" then
			local last_block = table.remove(block_stack)
			if last_block == "if" then
				table.insert(lines, indent .. "fi")
			elseif last_block == "for" or last_block == "while" then
				table.insert(lines, indent .. "done")
			elseif last_block == "function" then
				table.insert(lines, indent .. "}")
			end
		else
			local l = line:gsub("^%s*%-%-", indent .. "#")
			table.insert(lines, l)
		end
	end

	return table.concat(lines, "\n")
end

return M
