-- ============================================================================
-- KRS PLUGIN: Bun Debug Adapter -- `:KrsBunDapInstall`
-- ============================================================================
-- WHY THIS EXISTS
--   Bun speaks the WebKit inspector protocol, not CDP, so js-debug/pwa-node
--   cannot drive it -- which is why `type = "bun"` in a launch.json does nothing
--   in nvim. The only real translator is `packages/bun-debug-adapter-protocol`
--   in oven-sh/bun. The VSCode extension runs it INLINE
--   (vscode.DebugAdapterInlineImplementation), so it ships no CLI entry point,
--   and neither package is published to npm.
--
-- WHAT THE INSTALLER DOES
--   Sparse-checks-out those two packages (~6MB, blobless) into
--   `<data>/krs-bun-dap` and writes the missing entry point: the same adapter,
--   speaking DAP over stdin/stdout, which is the transport nvim-dap understands.
--
-- MAINTENANCE
--   `M.server_source` below IS the generated adapter. Edit it here, never in the
--   generated file: `setup()` rewrites the file whenever the two differ.
-- ============================================================================

local lazy_req = require("krs.core.lazy_require")
local path = lazy_req("krs.core.path")

local M = {}

-- ============================================================================
-- CONFIGURATION
-- ============================================================================

M.settings = {
	--- Where the sparse checkout and the generated adapter live.
	dir = path.normalize(vim.fn.stdpath("data") .. "/krs-bun-dap"),

	--- Repository the adapter packages come from.
	repo = "https://github.com/oven-sh/bun.git",

	--- Only these are checked out; the rest of the bun monorepo is ~2GB.
	packages = {
		"packages/bun-debug-adapter-protocol",
		"packages/bun-inspector-protocol",
	},

	--- Flat manifest written over bun's own workspace root package.json.
	--- `ws` is the inspector client; `source-map-js` is needed by sourcemap.ts for
	--- any TypeScript entry point.
	package_json = '{"name":"krs-bun-dap","private":true,"type":"module","dependencies":{"ws":"^8.18.3","source-map-js":"^1.2.1"}}',

	--- Notification title.
	notify_title = "Bun Debug Adapter",
}

--- Checkout directory (kept as a top-level field: other modules read it).
M.dir = M.settings.dir

--- Generated stdio DAP server that nvim-dap launches.
M.server = M.dir .. "/bun-dap.ts"

M.server_source = [==[
// Standalone stdio DAP server around Bun's own debug adapter.
// Generated by lua/plugins/krs/bun_dap.lua — edit there, not here.
import { DebugAdapter } from "./packages/bun-debug-adapter-protocol/index.ts";

const adapter = new DebugAdapter();

// Bun's adapter maps each requested breakpoint to its first resolved location
// (adapter.ts:784). When the inspector binds nothing — a blank line, a comment, any line
// with no executable code — that is `undefined`, and JSON.stringify turns it into a `null`
// hole in the breakpoints array. nvim-dap decodes null as vim.NIL and crashes indexing it
// ("attempt to index local 'state' (a userdata value)", breakpoints.lua:77). Replace the
// holes with what the spec asks for: an unverified breakpoint on the requested line.
const requestedBreakpointLines = new Map<number, (number | undefined)[]>();

function repairBreakpoints(message: any): void {
  const lines = requestedBreakpointLines.get(message.request_seq);
  requestedBreakpointLines.delete(message.request_seq);
  const breakpoints = message.body?.breakpoints;
  if (!lines || !Array.isArray(breakpoints)) return;
  for (let i = 0; i < breakpoints.length; i++) {
    breakpoints[i] ??= { verified: false, line: lines[i], message: "No code on this line." };
  }
}

let seq = 1;
function write(message: any): void {
  if (message.type === "response" && message.command === "setBreakpoints") repairBreakpoints(message);
  message.seq = seq++;
  const body = Buffer.from(JSON.stringify(message), "utf8");
  process.stdout.write(`Content-Length: ${body.byteLength}\r\n\r\n`);
  process.stdout.write(body);
}

adapter.on("Adapter.response", write);
adapter.on("Adapter.event", write);

adapter.on("Adapter.reverseRequest", ({ command, arguments: args }: any) => {
  write({ type: "request", command, arguments: args });
});

let buffer = Buffer.alloc(0);
process.stdin.on("data", (chunk: Buffer) => {
  buffer = Buffer.concat([buffer, chunk]);
  while (true) {
    const headerEnd = buffer.indexOf("\r\n\r\n");
    if (headerEnd < 0) return;
    const header = buffer.subarray(0, headerEnd).toString("utf8");
    const length = Number(/Content-Length: *(\d+)/i.exec(header)?.[1]);
    if (!Number.isFinite(length)) throw new Error(`Bad DAP header: ${header}`);
    const start = headerEnd + 4;
    if (buffer.byteLength < start + length) return;
    const message = JSON.parse(buffer.subarray(start, start + length).toString("utf8"));
    buffer = buffer.subarray(start + length);
    // Bun's adapter self-fires configurationDone() during initialize unless the
    // client claims supportsConfigurationDoneRequest — a non-standard field it reads
    // off the initialize *request*, which no DAP client sends (adapter.ts:521). That
    // sends Inspector.initialized before any setBreakpoints, so bun leaves wait=1 the
    // moment the inspector attaches and runs past every breakpoint. Claim it; nvim-dap
    // sends the real configurationDone after breakpoints are set, which is the point.
    if (message.command === "initialize") {
      (message.arguments ??= {}).supportsConfigurationDoneRequest = true;
    }
    if (message.command === "setBreakpoints") {
      const requested = message.arguments?.breakpoints ?? [];
      requestedBreakpointLines.set(message.seq, requested.map((bp: any) => bp?.line));
    }
    // Replies to reverse requests (runInTerminal) arrive as type "response"; the
    // adapter has no handler for those and forwarding one throws. Drop them.
    if (message.type === "request") adapter.emit("Adapter.request", message);
  }
});

process.stdin.on("end", () => {
  adapter.close();
  process.exit(0);
});
]==]

function M.installed()
	return vim.fn.filereadable(M.server) == 1 and vim.fn.isdirectory(M.dir .. "/node_modules/ws") == 1
end

local function notify(msg, level)
	vim.notify(msg, level or vim.log.levels.INFO, { title = M.settings.notify_title })
end

-- Runs the command list one after another, stopping on the first failure.
local function run_chain(steps, index, on_done)
	local step = steps[index]
	if not step then
		on_done(true)
		return
	end
	notify("⏳ [" .. index .. "/" .. #steps .. "] " .. table.concat(step.cmd, " "))
	vim.system(step.cmd, { cwd = step.cwd, text = true }, function(res)
		vim.schedule(function()
			if res.code ~= 0 then
				notify(
					"❌ Failed: " .. table.concat(step.cmd, " ") .. "\n" .. ((res.stderr or "") .. (res.stdout or "")),
					vim.log.levels.ERROR
				)
				on_done(false)
				return
			end
			run_chain(steps, index + 1, on_done)
		end)
	end)
end

function M.install(on_done)
	on_done = on_done or function() end

	if vim.fn.executable("bun") == 0 then
		notify("❌ `bun` is not on PATH — install Bun first.", vim.log.levels.ERROR)
		on_done(false)
		return
	end
	if vim.fn.executable("git") == 0 then
		notify("❌ `git` is not on PATH.", vim.log.levels.ERROR)
		on_done(false)
		return
	end

	local steps = {}
	if vim.fn.isdirectory(M.dir .. "/.git") == 0 then
		vim.fn.delete(M.dir, "rf")
		vim.fn.mkdir(vim.fn.fnamemodify(M.dir, ":h"), "p")
		table.insert(steps, {
			cmd = { "git", "clone", "--depth=1", "--filter=blob:none", "--sparse", M.settings.repo, M.dir },
		})
		table.insert(
			steps,
			{ cmd = vim.list_extend({ "git", "sparse-checkout", "set" }, M.settings.packages), cwd = M.dir }
		)
	else
		table.insert(steps, { cmd = { "git", "pull", "--ff-only" }, cwd = M.dir })
	end

	run_chain(steps, 1, function(ok)
		if not ok then
			on_done(false)
			return
		end
		-- The bun repo's own root package.json declares a `packages/*` workspace whose
		-- members want workspace-only deps, so `bun install` resolves nothing. Replace
		-- it (and drop the checked-out lockfiles) with a flat two-dependency manifest.
		vim.fn.writefile({ M.settings.package_json }, M.dir .. "/package.json")
		for _, lock in ipairs(vim.fn.glob(M.dir .. "/**/bun.lock*", false, true)) do
			vim.fn.delete(lock)
		end
		vim.fn.writefile(vim.split(M.server_source, "\n"), M.server)

		run_chain({ { cmd = { "bun", "install" }, cwd = M.dir } }, 1, function(installed)
			if installed then
				notify('✅ Bun debug adapter ready. `type = "bun"` launch configs now work.')
			end
			on_done(installed)
		end)
	end)
end

function M.setup()
	-- bun-dap.ts is generated from M.server_source above, so an existing install must
	-- pick up edits to it without a full re-clone.
	if M.installed() and table.concat(vim.fn.readfile(M.server), "\n") ~= M.server_source then
		vim.fn.writefile(vim.split(M.server_source, "\n"), M.server)
	end

	vim.api.nvim_create_user_command("KrsBunDapInstall", function()
		M.install()
	end, { desc = "Install/update the Bun debug adapter" })
end

-- Legacy global kept for user scripts and older keybinds that reference it.
_G.BunDap = M

-- ============================================================================
-- LAZY.NVIM SPEC
-- ============================================================================

return setmetatable({
	name = "krs_bun_dap",
	dir = require("krs.core.lazyspec").for_module(),
	cmd = "KrsBunDapInstall",
	config = M.setup,
}, { __index = M })
