#!/usr/bin/env bash
# ==============================================================================
# setup-bash.sh - Cross-Terminal Consistent Keybindings Manager for KRS Neovim
# Supports: Kitty, Foot, WezTerm, Alacritty, Termux, Windows Terminal
# ==============================================================================

set -e

COLOR_CYAN='\033[0;36m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_GRAY='\033[0;90m'
COLOR_NC='\033[0m'

echo -e "${COLOR_CYAN}============================================================${COLOR_NC}"
echo -e "${COLOR_CYAN} [*] KRS Neovim - Cross-Terminal Keybinds Configurator (Bash) ${COLOR_NC}"
echo -e "${COLOR_CYAN}============================================================${COLOR_NC}"

CHECK_ONLY=false
CONFIG_ALL=false
TARGET_TERM=""

for arg in "$@"; do
    case "$arg" in
        --check)
            CHECK_ONLY=true
            ;;
        --all)
            CONFIG_ALL=true
            ;;
        --term=*|-t=*)
            TARGET_TERM="${arg#*=}"
            ;;
        kitty|foot|wezterm|alacritty|termux|winter|wt)
            TARGET_TERM="$arg"
            ;;
    esac
done

# ------------------------------------------------------------------------------
# 1. Terminal Detection
# ------------------------------------------------------------------------------
detect_terminal() {
    if [ -n "$TERMUX_VERSION" ] || [ -d "/data/data/com.termux" ] || [[ "$PREFIX" == *"com.termux"* ]]; then
        echo "termux"
        return
    fi
    if [ -n "$KITTY_PID" ] || [ -n "$KITTY_WINDOW_ID" ] || [ "$TERM" = "xterm-kitty" ]; then
        echo "kitty"
        return
    fi
    if [ -n "$FOOT_TERMINAL_PID" ] || [[ "$TERM" =~ foot ]]; then
        echo "foot"
        return
    fi
    if [ -n "$WEZTERM_PANE" ] || [ -n "$WEZTERM_EXECUTABLE" ] || [ "$TERM_PROGRAM" = "WezTerm" ]; then
        echo "wezterm"
        return
    fi
    if [ -n "$ALACRITTY_WINDOW_ID" ] || [ -n "$ALACRITTY_LOG" ] || [ "$TERM" = "alacritty" ]; then
        echo "alacritty"
        return
    fi
    if [ -n "$WT_SESSION" ] || [ -n "$WT_PROFILE_ID" ]; then
        echo "winter"
        return
    fi
    echo "generic"
}

ACTIVE_TERM=$(detect_terminal)
echo -e "\n[*] Detected Active Terminal: ${COLOR_GREEN}${ACTIVE_TERM}${COLOR_NC}"

if [ "$CHECK_ONLY" = true ]; then
    echo -e "\n${COLOR_CYAN}[i] Check mode: Exiting without modifying configuration files.${COLOR_NC}"
    exit 0
fi

# ------------------------------------------------------------------------------
# 2. Config Handlers
# ------------------------------------------------------------------------------

# --- A. Kitty ---
configure_kitty() {
    echo -e "\n[*] Configuring Kitty Terminal..."
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
    local config_file="$config_dir/kitty.conf"

    mkdir -p "$config_dir"
    [ -f "$config_file" ] && cp -f "$config_file" "$config_file.backup"

    local start_marker="# >>> KRS NEOVIM CONSISTENT KEYBINDINGS >>>"
    local end_marker="# <<< KRS NEOVIM CONSISTENT KEYBINDINGS <<<"

    # Clean existing block
    if [ -f "$config_file" ]; then
        sed -i "/$start_marker/,/$end_marker/d" "$config_file"
    fi

    cat >> "$config_file" << 'EOF'
# >>> KRS NEOVIM CONSISTENT KEYBINDINGS >>>
# Automatically generated by setup-bash.sh for consistent Neovim keybinds
# Environments slot hopping (1..9)
map ctrl+shift+1 send_text all \x1b[49;6u
map ctrl+shift+2 send_text all \x1b[50;6u
map ctrl+shift+3 send_text all \x1b[51;6u
map ctrl+shift+4 send_text all \x1b[52;6u
map ctrl+shift+5 send_text all \x1b[53;6u
map ctrl+shift+6 send_text all \x1b[54;6u
map ctrl+shift+7 send_text all \x1b[55;6u
map ctrl+shift+8 send_text all \x1b[56;6u
map ctrl+shift+9 send_text all \x1b[57;6u

# Feature letters (Environments Menu, Command Palette, Workspaces, Git Center)
map ctrl+shift+e send_text all \x1b[69;6u
map ctrl+shift+p send_text all \x1b[80;6u
map ctrl+shift+w send_text all \x1b[87;6u
map ctrl+shift+g send_text all \x1b[71;6u
map ctrl+shift+f send_text all \x1b[70;6u
map ctrl+shift+r send_text all \x1b[82;6u
map ctrl+shift+t send_text all \x1b[84;6u
map ctrl+shift+q send_text all \x1b[81;6u
map ctrl+shift+s send_text all \x1b[83;6u

# Terminal drawer toggle & special keys
map ctrl+; send_text all \x1b[59;5u
map ctrl+, send_text all \x1b[44;5u
map ctrl+. send_text all \x1b[46;5u
map ctrl+/ send_text all \x1b[47;5u
map ctrl+shift+space send_text all \x1b[32;6u
# <<< KRS NEOVIM CONSISTENT KEYBINDINGS <<<
EOF
    echo -e "   ${COLOR_GREEN}[+] Kitty configuration written to $config_file${COLOR_NC}"
}

# --- B. Foot ---
configure_foot() {
    echo -e "\n[*] Configuring Foot Terminal (Wayland)..."
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/foot"
    local config_file="$config_dir/foot.ini"

    mkdir -p "$config_dir"
    [ -f "$config_file" ] && cp -f "$config_file" "$config_file.backup"

    local start_marker="# >>> KRS NEOVIM FOOT BINDINGS >>>"
    local end_marker="# <<< KRS NEOVIM FOOT BINDINGS <<<"

    if [ -f "$config_file" ]; then
        sed -i "/$start_marker/,/$end_marker/d" "$config_file"
    fi

    cat >> "$config_file" << 'EOF'
# >>> KRS NEOVIM FOOT BINDINGS >>>
[key-bindings]
# Unbind conflicting tab / window hotkeys so they flow cleanly to Neovim
# (Foot natively supports CSI u protocol)
# <<< KRS NEOVIM FOOT BINDINGS <<<
EOF
    echo -e "   ${COLOR_GREEN}[+] Foot configuration written to $config_file${COLOR_NC}"
}

# --- C. WezTerm ---
configure_wezterm() {
    echo -e "\n[*] Configuring WezTerm..."
    local config_file="$HOME/.wezterm.lua"
    if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.lua" ]; then
        config_file="${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.lua"
    fi

    mkdir -p "$(dirname "$config_file")"
    [ -f "$config_file" ] && cp -f "$config_file" "$config_file.backup"

    local start_marker="-- >>> KRS NEOVIM WEZTERM BINDINGS >>>"
    local end_marker="-- <<< KRS NEOVIM WEZTERM BINDINGS <<<"

    if [ -f "$config_file" ]; then
        sed -i "/$start_marker/,/$end_marker/d" "$config_file"
    fi

    cat >> "$config_file" << 'EOF'
-- >>> KRS NEOVIM WEZTERM BINDINGS >>>
local function apply_krs_keys(config)
  config.keys = config.keys or {}
  local wez = require('wezterm')
  local function bind_csi(key, mods, csi)
    table.insert(config.keys, { key = key, mods = mods, action = wez.action.SendString(csi) })
  end
  -- Environments 1..9
  for i = 1, 9 do
    bind_csi(tostring(i), 'CTRL|SHIFT', string.format('\x1b[%d;6u', 48 + i))
  end
  -- Feature shortcuts
  bind_csi('e', 'CTRL|SHIFT', '\x1b[69;6u')
  bind_csi('p', 'CTRL|SHIFT', '\x1b[80;6u')
  bind_csi('w', 'CTRL|SHIFT', '\x1b[87;6u')
  bind_csi('g', 'CTRL|SHIFT', '\x1b[71;6u')
  bind_csi('f', 'CTRL|SHIFT', '\x1b[70;6u')
  bind_csi('r', 'CTRL|SHIFT', '\x1b[82;6u')
  bind_csi('t', 'CTRL|SHIFT', '\x1b[84;6u')
  bind_csi('q', 'CTRL|SHIFT', '\x1b[81;6u')
  bind_csi('s', 'CTRL|SHIFT', '\x1b[83;6u')
  bind_csi(';', 'CTRL', '\x1b[59;5u')
end
if config then apply_krs_keys(config) end
-- <<< KRS NEOVIM WEZTERM BINDINGS <<<
EOF
    echo -e "   ${COLOR_GREEN}[+] WezTerm configuration written to $config_file${COLOR_NC}"
}

# --- D. Alacritty ---
configure_alacritty() {
    echo -e "\n[*] Configuring Alacritty..."
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
    local config_file="$config_dir/alacritty.toml"

    mkdir -p "$config_dir"
    [ -f "$config_file" ] && cp -f "$config_file" "$config_file.backup"

    local start_marker="# >>> KRS NEOVIM ALACRITTY BINDINGS >>>"
    local end_marker="# <<< KRS NEOVIM ALACRITTY BINDINGS <<<"

    if [ -f "$config_file" ]; then
        sed -i "/$start_marker/,/$end_marker/d" "$config_file"
    fi

    cat >> "$config_file" << 'EOF'
# >>> KRS NEOVIM ALACRITTY BINDINGS >>>
# Environment slot navigation
[[keyboard.bindings]]
key = "1"
mods = "Control|Shift"
chars = "\u001b[49;6u"

[[keyboard.bindings]]
key = "2"
mods = "Control|Shift"
chars = "\u001b[50;6u"

[[keyboard.bindings]]
key = "3"
mods = "Control|Shift"
chars = "\u001b[51;6u"

[[keyboard.bindings]]
key = "4"
mods = "Control|Shift"
chars = "\u001b[52;6u"

[[keyboard.bindings]]
key = "5"
mods = "Control|Shift"
chars = "\u001b[53;6u"

[[keyboard.bindings]]
key = "6"
mods = "Control|Shift"
chars = "\u001b[54;6u"

[[keyboard.bindings]]
key = "7"
mods = "Control|Shift"
chars = "\u001b[55;6u"

[[keyboard.bindings]]
key = "8"
mods = "Control|Shift"
chars = "\u001b[56;6u"

[[keyboard.bindings]]
key = "9"
mods = "Control|Shift"
chars = "\u001b[57;6u"

[[keyboard.bindings]]
key = "E"
mods = "Control|Shift"
chars = "\u001b[69;6u"

[[keyboard.bindings]]
key = "P"
mods = "Control|Shift"
chars = "\u001b[80;6u"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u001b[87;6u"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
chars = "\u001b[71;6u"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u001b[59;5u"
# <<< KRS NEOVIM ALACRITTY BINDINGS <<<
EOF
    echo -e "   ${COLOR_GREEN}[+] Alacritty configuration written to $config_file${COLOR_NC}"
}

# --- E. Termux ---
configure_termux() {
    echo -e "\n[*] Configuring Termux (Android)..."
    local termux_dir="$HOME/.termux"
    local config_file="$termux_dir/termux.properties"

    mkdir -p "$termux_dir"
    [ -f "$config_file" ] && cp -f "$config_file" "$config_file.backup"

    local start_marker="# >>> KRS NEOVIM TERMUX SHORTCUTS >>>"
    local end_marker="# <<< KRS NEOVIM TERMUX SHORTCUTS <<<"

    if [ -f "$config_file" ]; then
        sed -i "/$start_marker/,/$end_marker/d" "$config_file"
    fi

    cat >> "$config_file" << 'EOF'
# >>> KRS NEOVIM TERMUX SHORTCUTS >>>
# Quick-access extra keys for KRS Neovim Environments and Navigation
extra-keys = [ \
  ['ESC', 'CTRL', 'ALT', 'TAB', 'SHIFT', 'UP', 'DOWN'], \
  [{macro: "\033[69;6u", display: "ENV"}, {macro: "\033[49;6u", display: "E1"}, {macro: "\033[50;6u", display: "E2"}, {macro: "\033[51;6u", display: "E3"}, 'LEFT', 'RIGHT', 'ENTER'] \
]
ctrl-space-workaround = true
shortcut.create-session = false
# <<< KRS NEOVIM TERMUX SHORTCUTS <<<
EOF
    echo -e "   ${COLOR_GREEN}[+] Termux configuration written to $config_file${COLOR_NC}"
    echo -e "   ${COLOR_CYAN}[i] Run 'termux-reload-settings' inside Termux to reload configuration.${COLOR_NC}"
}

# --- F. Windows Terminal (WSL / Git Bash bridge) ---
configure_winter() {
    echo -e "\n[*] Windows Terminal detected. Triggering PowerShell setup bridge..."
    if command -v powershell.exe >/dev/null 2>&1; then
        local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$script_dir/setup-powershell.ps1"
    else
        echo -e "   ${COLOR_YELLOW}[!] powershell.exe not available in current PATH.${COLOR_NC}"
    fi
}

# ------------------------------------------------------------------------------
# 3. Execution Dispatch
# ------------------------------------------------------------------------------
if [ "$CONFIG_ALL" = true ]; then
    echo -e "\n${COLOR_YELLOW}[*] Configuring ALL supported terminals on system...${COLOR_NC}"
    configure_kitty
    configure_foot
    configure_wezterm
    configure_alacritty
    configure_termux
    [ "$ACTIVE_TERM" = "winter" ] && configure_winter
elif [ -n "$TARGET_TERM" ]; then
    case "$TARGET_TERM" in
        kitty) configure_kitty ;;
        foot) configure_foot ;;
        wezterm) configure_wezterm ;;
        alacritty) configure_alacritty ;;
        termux) configure_termux ;;
        winter|wt) configure_winter ;;
        *) echo -e "${COLOR_RED}Unknown terminal '$TARGET_TERM'. Choose: kitty, foot, wezterm, alacritty, termux, winter.${COLOR_NC}" ;;
    esac
else
    case "$ACTIVE_TERM" in
        kitty) configure_kitty ;;
        foot) configure_foot ;;
        wezterm) configure_wezterm ;;
        alacritty) configure_alacritty ;;
        termux) configure_termux ;;
        winter) configure_winter ;;
        *)
            echo -e "${COLOR_YELLOW}[*] Configuring default desktop terminal configs (Kitty, WezTerm, Alacritty)...${COLOR_NC}"
            configure_kitty
            configure_wezterm
            configure_alacritty
            ;;
    esac
fi

echo -e "\n${COLOR_GREEN}============================================================${COLOR_NC}"
echo -e "${COLOR_GREEN} [OK] Cross-terminal keybindings configured successfully!   ${COLOR_NC}"
echo -e "${COLOR_GREEN}============================================================${COLOR_NC}"
echo -e "Restart your terminal emulator or reload its configuration to apply."
